/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FocusCalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  workDurationMinutes: 40,
  breakDurationMinutes: 10,
  dataDirectory: "CalendarData",
  autoStartBreak: false,
  soundFilePath: ""
};

// src/storage.ts
var import_obsidian = require("obsidian");
var StorageManager = class {
  constructor(app, settingsGetter) {
    this.isLocalSaving = false;
    this.app = app;
    this.settingsGetter = settingsGetter;
  }
  get dataFolder() {
    return (0, import_obsidian.normalizePath)(this.settingsGetter().dataDirectory || "CalendarData");
  }
  async ensureDataFolderExists() {
    const folderPath = this.dataFolder;
    const exists = await this.app.vault.adapter.exists(folderPath);
    if (!exists) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  getMonthFilePath(yearMonth) {
    return (0, import_obsidian.normalizePath)(`${this.dataFolder}/entries-${yearMonth}.json`);
  }
  getPomodoroLogFilePath(yearMonth) {
    return (0, import_obsidian.normalizePath)(`${this.dataFolder}/pomodoro-logs-${yearMonth}.json`);
  }
  async loadEntriesForMonth(yearMonth) {
    await this.ensureDataFolderExists();
    const path = this.getMonthFilePath(yearMonth);
    try {
      const exists = await this.app.vault.adapter.exists(path);
      if (!exists) {
        const seedEntries = this.generateSeedEntries(yearMonth);
        await this.saveEntriesForMonth(yearMonth, seedEntries);
        await this.generateSeedPomodoroLogs(yearMonth, seedEntries);
        return seedEntries;
      }
      const content = await this.app.vault.adapter.read(path);
      return JSON.parse(content);
    } catch (e) {
      console.error(`Failed to read calendar entries for ${yearMonth}:`, e);
      return [];
    }
  }
  async saveEntriesForMonth(yearMonth, entries) {
    await this.ensureDataFolderExists();
    const path = this.getMonthFilePath(yearMonth);
    const data = JSON.stringify(entries, null, 2);
    this.isLocalSaving = true;
    await this.app.vault.adapter.write(path, data);
    setTimeout(() => {
      this.isLocalSaving = false;
    }, 500);
  }
  async saveEntry(entry) {
    const yearMonth = entry.date.substring(0, 7);
    const currentEntries = await this.loadEntriesForMonth(yearMonth);
    const existingIdx = currentEntries.findIndex((e) => e.id === entry.id);
    if (existingIdx >= 0) {
      currentEntries[existingIdx] = entry;
    } else {
      currentEntries.push(entry);
    }
    await this.saveEntriesForMonth(yearMonth, currentEntries);
  }
  async deleteEntry(entryId, date) {
    const yearMonth = date.substring(0, 7);
    const currentEntries = await this.loadEntriesForMonth(yearMonth);
    const filtered = currentEntries.filter((e) => e.id !== entryId);
    await this.saveEntriesForMonth(yearMonth, filtered);
  }
  async logPomodoroSession(session) {
    await this.ensureDataFolderExists();
    const yearMonth = session.date.substring(0, 7);
    const path = this.getPomodoroLogFilePath(yearMonth);
    let logs = [];
    try {
      if (await this.app.vault.adapter.exists(path)) {
        const content = await this.app.vault.adapter.read(path);
        logs = JSON.parse(content);
      }
    } catch (e) {
      logs = [];
    }
    logs.push(session);
    this.isLocalSaving = true;
    await this.app.vault.adapter.write(path, JSON.stringify(logs, null, 2));
    setTimeout(() => {
      this.isLocalSaving = false;
    }, 500);
    if (session.taskId && session.type === "work") {
      const entries = await this.loadEntriesForMonth(yearMonth);
      const entry = entries.find((e) => e.id === session.taskId);
      if (entry) {
        entry.actualSecondsSpent = (entry.actualSecondsSpent || 0) + session.durationSeconds;
        entry.updatedAt = Date.now();
        await this.saveEntriesForMonth(yearMonth, entries);
      }
    }
  }
  async loadPomodoroLogsForMonth(yearMonth) {
    await this.ensureDataFolderExists();
    const path = this.getPomodoroLogFilePath(yearMonth);
    try {
      if (!await this.app.vault.adapter.exists(path))
        return [];
      const content = await this.app.vault.adapter.read(path);
      return JSON.parse(content);
    } catch (e) {
      return [];
    }
  }
  generateSeedEntries(yearMonth) {
    const now = /* @__PURE__ */ new Date();
    const currentDay = now.getDate().toString().padStart(2, "0");
    return [
      {
        id: "seed-event-1",
        title: "Computer Systems Exam",
        date: `${yearMonth}-15`,
        startTime: "09:00",
        endTime: "11:00",
        type: "event",
        createdAt: Date.now(),
        updatedAt: Date.now()
      },
      {
        id: "seed-event-2",
        title: "Algorithms & Data Structures Exam",
        date: `${yearMonth}-22`,
        startTime: "14:00",
        endTime: "16:00",
        type: "event",
        createdAt: Date.now(),
        updatedAt: Date.now()
      },
      {
        id: "seed-event-3",
        title: "Project Milestone Release",
        date: `${yearMonth}-28`,
        startTime: "10:00",
        endTime: "12:00",
        type: "event",
        createdAt: Date.now(),
        updatedAt: Date.now()
      },
      {
        id: "seed-task-1",
        title: "Review Chapter 4 Practice Problems",
        date: `${yearMonth}-${currentDay}`,
        startTime: "08:00",
        endTime: "09:30",
        type: "task",
        actualSecondsSpent: 4800,
        createdAt: Date.now(),
        updatedAt: Date.now()
      },
      {
        id: "seed-task-2",
        title: "Lab Assignment Draft",
        date: `${yearMonth}-${currentDay}`,
        startTime: "11:00",
        endTime: "13:00",
        type: "task",
        actualSecondsSpent: 7200,
        createdAt: Date.now(),
        updatedAt: Date.now()
      },
      {
        id: "seed-task-3",
        title: "System Architecture Diagram",
        date: `${yearMonth}-${currentDay}`,
        startTime: "14:00",
        endTime: "16:00",
        type: "task",
        actualSecondsSpent: 4800,
        createdAt: Date.now(),
        updatedAt: Date.now()
      }
    ];
  }
  async generateSeedPomodoroLogs(yearMonth, seedEntries) {
    const path = this.getPomodoroLogFilePath(yearMonth);
    const now = /* @__PURE__ */ new Date();
    const todayStr = now.toISOString().substring(0, 10);
    const logs = [
      {
        id: "log-1",
        taskId: seedEntries[3].id,
        taskTitle: seedEntries[3].title,
        type: "work",
        durationSeconds: 2400,
        completedAt: Date.now() - 864e5,
        date: todayStr
      },
      {
        id: "log-2",
        taskId: seedEntries[3].id,
        taskTitle: seedEntries[3].title,
        type: "work",
        durationSeconds: 2400,
        completedAt: Date.now() - 828e5,
        date: todayStr
      },
      {
        id: "log-3",
        taskId: seedEntries[4].id,
        taskTitle: seedEntries[4].title,
        type: "work",
        durationSeconds: 2400,
        completedAt: Date.now() - 432e5,
        date: todayStr
      },
      {
        id: "log-4",
        taskId: seedEntries[4].id,
        taskTitle: seedEntries[4].title,
        type: "work",
        durationSeconds: 2400,
        completedAt: Date.now() - 396e5,
        date: todayStr
      },
      {
        id: "log-5",
        taskId: seedEntries[4].id,
        taskTitle: seedEntries[4].title,
        type: "work",
        durationSeconds: 2400,
        completedAt: Date.now() - 36e6,
        date: todayStr
      }
    ];
    this.isLocalSaving = true;
    await this.app.vault.adapter.write(path, JSON.stringify(logs, null, 2));
    setTimeout(() => {
      this.isLocalSaving = false;
    }, 500);
  }
};

// src/pomodoro.ts
var PomodoroManager = class {
  constructor(settingsGetter, onStateChange, onSessionComplete, playAudioCallback, onBreakStartCallback) {
    this.mode = "work";
    this.isRunning = false;
    this.timeLeftSeconds = 40 * 60;
    this.totalDurationSeconds = 40 * 60;
    this.timerId = null;
    this.focusedTask = null;
    this.settingsGetter = settingsGetter;
    this.onStateChange = onStateChange;
    this.onSessionComplete = onSessionComplete;
    this.playAudioCallback = playAudioCallback;
    this.onBreakStartCallback = onBreakStartCallback;
    this.resetTimer();
  }
  getSettings() {
    return this.settingsGetter();
  }
  getState() {
    return {
      mode: this.mode,
      isRunning: this.isRunning,
      timeLeftSeconds: this.timeLeftSeconds,
      totalDurationSeconds: this.totalDurationSeconds,
      focusedTask: this.focusedTask
    };
  }
  setFocusedTask(task) {
    this.focusedTask = task;
    this.notifyState();
  }
  getFocusedTask() {
    return this.focusedTask;
  }
  start() {
    if (this.isRunning)
      return;
    this.isRunning = true;
    this.timerId = window.setInterval(() => this.tick(), 1e3);
    this.notifyState();
  }
  pause() {
    if (!this.isRunning)
      return;
    this.isRunning = false;
    if (this.timerId !== null) {
      clearInterval(this.timerId);
      this.timerId = null;
    }
    this.notifyState();
  }
  togglePlayPause() {
    if (this.isRunning) {
      this.pause();
    } else {
      this.start();
    }
  }
  resetTimer() {
    this.pause();
    const settings = this.settingsGetter();
    if (this.mode === "work") {
      this.totalDurationSeconds = (settings.workDurationMinutes || 40) * 60;
    } else {
      this.totalDurationSeconds = (settings.breakDurationMinutes || 10) * 60;
    }
    this.timeLeftSeconds = this.totalDurationSeconds;
    this.notifyState();
  }
  switchMode(newMode) {
    this.pause();
    this.mode = newMode || (this.mode === "work" ? "break" : "work");
    if (this.mode === "break" && this.onBreakStartCallback) {
      this.onBreakStartCallback();
    }
    this.resetTimer();
  }
  tick() {
    if (this.timeLeftSeconds > 0) {
      this.timeLeftSeconds--;
      this.notifyState();
    } else {
      this.onCompleted();
    }
  }
  onCompleted() {
    this.pause();
    const settings = this.settingsGetter();
    const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    const session = {
      id: "session-" + Date.now(),
      taskId: this.focusedTask ? this.focusedTask.id : void 0,
      taskTitle: this.focusedTask ? this.focusedTask.title : void 0,
      type: this.mode,
      durationSeconds: this.totalDurationSeconds,
      completedAt: Date.now(),
      date: today
    };
    this.onSessionComplete(session);
    if (settings.soundFilePath && settings.soundFilePath.trim() !== "") {
      if (this.playAudioCallback) {
        this.playAudioCallback(settings.soundFilePath.trim());
      }
    }
    this.mode = this.mode === "work" ? "break" : "work";
    if (this.mode === "break" && this.onBreakStartCallback) {
      this.onBreakStartCallback();
    }
    this.resetTimer();
    if (settings.autoStartBreak && this.mode === "break") {
      this.start();
    }
  }
  notifySettingsUpdated() {
    if (!this.isRunning) {
      this.resetTimer();
    }
  }
  notifyState() {
    this.onStateChange(this.getState());
  }
};

// src/views/CalendarView.ts
var import_obsidian3 = require("obsidian");

// src/views/PomodoroHeader.ts
var PomodoroHeaderComponent = class {
  constructor(containerEl, pomodoroManager, viewMode, totalHours, imminentEvent = null) {
    this.containerEl = containerEl;
    this.pomodoroManager = pomodoroManager;
    this.viewMode = viewMode;
    this.totalHours = totalHours;
    this.imminentEvent = imminentEvent;
    this.render();
  }
  update(viewMode, totalHours, imminentEvent = null) {
    this.viewMode = viewMode;
    this.totalHours = totalHours;
    this.imminentEvent = imminentEvent;
    this.render();
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("fcp-pomodoro-header");
    if (this.viewMode === "month") {
      this.containerEl.addClass("month-mode");
      this.renderMonthHeader();
    } else {
      this.containerEl.removeClass("month-mode");
      this.renderWeekHeader();
    }
  }
  renderMonthHeader() {
    const leftDiv = this.containerEl.createDiv("fcp-pomo-left-imminent");
    if (this.imminentEvent) {
      let daysStr = "";
      if (this.imminentEvent.daysAway === 0) {
        daysStr = "today";
      } else if (this.imminentEvent.daysAway === 1) {
        daysStr = "1 day away";
      } else {
        daysStr = `${this.imminentEvent.daysAway} days away`;
      }
      leftDiv.innerHTML = `
        <span class="fcp-imminent-badge">UPCOMING EVENT</span>
        <span class="fcp-imminent-text"><strong>${this.escapeHtml(this.imminentEvent.title)}</strong> is ${daysStr}</span>
      `;
    } else {
      leftDiv.innerHTML = `<span class="fcp-imminent-text muted">No upcoming events</span>`;
    }
    const rightSection = this.containerEl.createDiv("fcp-pomo-right");
    const hoursCard = rightSection.createDiv("fcp-hours-card");
    hoursCard.innerHTML = `
      <div class="fcp-hours-val">${this.totalHours.toFixed(1)} <span class="fcp-hours-unit">HRS</span></div>
      <div class="fcp-hours-sub">THIS MONTH</div>
    `;
  }
  renderWeekHeader() {
    const state = this.pomodoroManager.getState();
    const isWork = state.mode === "work";
    const accentColor = isWork ? "var(--fcp-red-accent, #ef4444)" : "var(--fcp-blue-accent, #3b82f6)";
    const modeLabel = isWork ? "WORK" : "BREAK";
    this.containerEl.createDiv("fcp-pomo-left-spacer");
    const centerSection = this.containerEl.createDiv("fcp-pomo-center");
    const svgSize = 64;
    const strokeWidth = 5;
    const radius = (svgSize - strokeWidth) / 2;
    const circumference = 2 * Math.PI * radius;
    const progressRatio = state.totalDurationSeconds > 0 ? state.timeLeftSeconds / state.totalDurationSeconds : 0;
    const strokeDashoffset = circumference * (1 - progressRatio);
    const minutes = Math.floor(state.timeLeftSeconds / 60);
    const seconds = state.timeLeftSeconds % 60;
    const formattedTime = `${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`;
    const svgWrapper = centerSection.createDiv("fcp-radial-wrapper");
    svgWrapper.style.setProperty("--accent-color", accentColor);
    svgWrapper.innerHTML = `
      <svg width="${svgSize}" height="${svgSize}" viewBox="0 0 ${svgSize} ${svgSize}" class="fcp-radial-svg">
        <circle
          cx="${svgSize / 2}" cy="${svgSize / 2}" r="${radius}"
          fill="none" stroke="var(--background-modifier-border)" stroke-width="${strokeWidth}"
        />
        <circle
          cx="${svgSize / 2}" cy="${svgSize / 2}" r="${radius}"
          fill="none" stroke="${accentColor}" stroke-width="${strokeWidth}"
          stroke-linecap="round"
          stroke-dasharray="${circumference}"
          stroke-dashoffset="${strokeDashoffset}"
          transform="rotate(-90 ${svgSize / 2} ${svgSize / 2})"
          style="transition: stroke-dashoffset 0.3s ease, stroke 0.3s ease;"
        />
      </svg>
      <div class="fcp-radial-text">${formattedTime}</div>
    `;
    const controlsDiv = centerSection.createDiv("fcp-pomo-controls");
    const modeBadge = controlsDiv.createDiv("fcp-mode-badge");
    modeBadge.textContent = modeLabel;
    modeBadge.style.color = accentColor;
    modeBadge.style.borderColor = accentColor;
    const btnGroup = controlsDiv.createDiv("fcp-btn-group");
    const playPauseBtn = btnGroup.createEl("button", {
      cls: "fcp-icon-btn fcp-play-btn",
      ariaLabel: state.isRunning ? "Pause" : "Start"
    });
    playPauseBtn.innerHTML = state.isRunning ? `<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>` : `<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>`;
    playPauseBtn.onclick = () => this.pomodoroManager.togglePlayPause();
    const resetBtn = btnGroup.createEl("button", {
      cls: "fcp-icon-btn",
      ariaLabel: "Reset"
    });
    resetBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>`;
    resetBtn.onclick = () => this.pomodoroManager.resetTimer();
    const skipBtn = btnGroup.createEl("button", {
      cls: "fcp-icon-btn",
      ariaLabel: "Switch Mode"
    });
    skipBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="5 4 15 12 5 20 5 4"/><line x1="19" y1="5" x2="19" y2="19"/></svg>`;
    skipBtn.onclick = () => this.pomodoroManager.switchMode();
    const rightSection = this.containerEl.createDiv("fcp-pomo-right");
    const hoursCard = rightSection.createDiv("fcp-hours-card");
    hoursCard.innerHTML = `
      <div class="fcp-hours-val">${this.totalHours.toFixed(1)} <span class="fcp-hours-unit">HRS</span></div>
      <div class="fcp-hours-sub">THIS WEEK</div>
    `;
  }
  escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }
};

// src/views/WeekViewRender.ts
var import_obsidian2 = require("obsidian");
var WeekViewRenderComponent = class {
  // pixels per 30 minutes (52 / 2)
  constructor(containerEl, weekStart, entries, callbacks) {
    // Constants for 30-minute precision snapping
    this.startHour = 5;
    // 05:00
    this.endHour = 24;
    // 24:00
    this.totalHours = 19;
    // 5..24
    this.hourHeight = 52;
    // pixels per hour
    this.slotHeight = 26;
    this.containerEl = containerEl;
    this.weekStart = weekStart;
    this.entries = entries;
    this.callbacks = callbacks;
    this.render();
  }
  update(weekStart, entries) {
    this.weekStart = weekStart;
    this.entries = entries;
    this.render();
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("fcp-week-view-wrapper");
    const weekDates = [];
    for (let i = 0; i < 7; i++) {
      const d = new Date(this.weekStart);
      d.setDate(d.getDate() + i);
      weekDates.push(d);
    }
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    const headerRow = this.containerEl.createDiv("fcp-week-header");
    headerRow.createDiv("fcp-time-gutter-header");
    const daysHeaderGrid = headerRow.createDiv("fcp-week-days-header-grid");
    weekDates.forEach((date) => {
      const dateStr = this.formatDateIso(date);
      const isToday = dateStr === todayStr;
      const dayColHeader = daysHeaderGrid.createDiv(`fcp-day-header-cell ${isToday ? "is-today" : ""}`);
      const dayName = date.toLocaleDateString("en-US", { weekday: "short" });
      const dayNum = date.getDate();
      dayColHeader.innerHTML = `
        <div class="fcp-day-name">${dayName}</div>
        <div class="fcp-day-num">${dayNum}</div>
      `;
    });
    const gridBody = this.containerEl.createDiv("fcp-week-grid-body");
    const timeGutter = gridBody.createDiv("fcp-time-gutter");
    for (let h = this.startHour; h <= this.endHour; h++) {
      const timeLabel = timeGutter.createDiv("fcp-time-label");
      timeLabel.style.height = `${this.hourHeight}px`;
      const hourStr = h < 24 ? `${h.toString().padStart(2, "0")}:00` : "24:00";
      timeLabel.textContent = hourStr;
    }
    const columnsContainer = gridBody.createDiv("fcp-columns-container");
    columnsContainer.style.height = `${this.totalHours * this.hourHeight}px`;
    const gridLines = columnsContainer.createDiv("fcp-grid-lines");
    for (let h = 0; h < this.totalHours; h++) {
      const line = gridLines.createDiv("fcp-grid-line");
      line.style.top = `${h * this.hourHeight}px`;
      line.style.height = `${this.slotHeight}px`;
      const halfLine = gridLines.createDiv("fcp-grid-line-half");
      halfLine.style.top = `${(h + 0.5) * this.hourHeight}px`;
      halfLine.style.height = `${this.slotHeight}px`;
    }
    weekDates.forEach((date, colIndex) => {
      const dateStr = this.formatDateIso(date);
      const colEl = columnsContainer.createDiv("fcp-day-column");
      colEl.dataset.date = dateStr;
      colEl.dataset.colIndex = colIndex.toString();
      colEl.addEventListener("click", async (e) => {
        if (e.target.closest(".fcp-entry-card"))
          return;
        const rect = colEl.getBoundingClientRect();
        const offsetY = e.clientY - rect.top;
        const slotIndex = Math.floor(offsetY / this.slotHeight);
        const maxSlots = this.totalHours * 2;
        const clampedSlot = Math.max(0, Math.min(slotIndex, maxSlots - 1));
        const startMinutes = this.startHour * 60 + clampedSlot * 30;
        const endMinutes = Math.min(startMinutes + 30, this.endHour * 60);
        const startTime = this.minutesToTimeStr(startMinutes);
        const endTime = this.minutesToTimeStr(endMinutes);
        const newEntry = await this.callbacks.onEntryCreate(dateStr, startTime, endTime);
        const newCard = this.renderEntryCard(colEl, newEntry);
        this.enableCardInlineEdit(newCard, newEntry);
      });
      const dayEntries = this.entries.filter((e) => e.date === dateStr);
      dayEntries.forEach((entry) => {
        this.renderEntryCard(colEl, entry);
      });
    });
    setTimeout(() => {
      const scrollbarWidth = gridBody.offsetWidth - gridBody.clientWidth;
      if (scrollbarWidth > 0) {
        headerRow.style.paddingRight = `${scrollbarWidth}px`;
      } else {
        headerRow.style.paddingRight = "0px";
      }
    }, 0);
  }
  renderEntryCard(columnEl, entry) {
    const startMins = this.snapTo30Min(this.timeStrToMinutes(entry.startTime));
    let endMins = this.snapTo30Min(this.timeStrToMinutes(entry.endTime));
    if (endMins <= startMins) {
      endMins = startMins + 30;
    }
    entry.startTime = this.minutesToTimeStr(startMins);
    entry.endTime = this.minutesToTimeStr(endMins);
    const minStartScale = this.startHour * 60;
    const maxEndScale = this.endHour * 60;
    const clampedStart = Math.max(minStartScale, Math.min(startMins, maxEndScale));
    const clampedEnd = Math.max(clampedStart + 30, Math.min(endMins, maxEndScale));
    const topPx = Math.round((clampedStart - minStartScale) / 30) * this.slotHeight;
    const durationSlots = Math.max(1, Math.round((clampedEnd - clampedStart) / 30));
    const heightPx = durationSlots * this.slotHeight;
    const isFocused = this.callbacks.getFocusedTaskId() === entry.id;
    const isShort = durationSlots <= 1;
    const card = columnEl.createDiv(`fcp-entry-card type-${entry.type} ${isFocused ? "is-focused" : ""} ${isShort ? "is-short" : ""}`);
    card.style.top = `${topPx}px`;
    card.style.height = `${heightPx}px`;
    card.dataset.id = entry.id;
    card.createDiv("fcp-resize-handle top");
    card.createDiv("fcp-resize-handle bottom");
    const content = card.createDiv("fcp-entry-content");
    content.innerHTML = `
      <div class="fcp-entry-title">${this.escapeHtml(entry.title || "Untitled")}</div>
      <div class="fcp-entry-time">${entry.startTime} - ${entry.endTime}</div>
    `;
    card.addEventListener("click", (e) => {
      if (card.classList.contains("is-editing"))
        return;
      e.stopPropagation();
      this.callbacks.onTaskFocus(entry);
    });
    card.addEventListener("dblclick", (e) => {
      e.stopPropagation();
      this.enableCardInlineEdit(card, entry);
    });
    card.addEventListener("contextmenu", (e) => {
      if (card.classList.contains("is-editing"))
        return;
      e.preventDefault();
      e.stopPropagation();
      const menu = new import_obsidian2.Menu();
      menu.addItem((item) => {
        item.setTitle("Rename Entry").setIcon("lucide-edit-3").onClick(() => {
          this.enableCardInlineEdit(card, entry);
        });
      });
      menu.addItem((item) => {
        const nextType = entry.type === "task" ? "Event (Green)" : "Task (Pastel Blue)";
        item.setTitle(`Change to ${nextType}`).setIcon("lucide-refresh-cw").onClick(async () => {
          entry.type = entry.type === "task" ? "event" : "task";
          card.className = `fcp-entry-card type-${entry.type} ${this.callbacks.getFocusedTaskId() === entry.id ? "is-focused" : ""}`;
          await this.callbacks.onEntryUpdate(entry);
        });
      });
      menu.addItem((item) => {
        item.setTitle("Focus Pomodoro Timer").setIcon("lucide-timer").onClick(() => {
          this.callbacks.onTaskFocus(entry);
        });
      });
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("Delete Entry").setIcon("lucide-trash-2").onClick(async () => {
          card.remove();
          await this.callbacks.onEntryDelete(entry);
        });
      });
      menu.showAtMouseEvent(e);
    });
    this.setupCardDrag(card, entry);
    return card;
  }
  enableCardInlineEdit(card, entry) {
    const content = card.querySelector(".fcp-entry-content");
    if (!content || card.classList.contains("is-editing"))
      return;
    card.addClass("is-editing");
    content.innerHTML = "";
    const input = document.createElement("input");
    input.type = "text";
    input.className = "fcp-inline-input";
    input.value = entry.title || "";
    content.appendChild(input);
    let isReady = false;
    setTimeout(() => {
      isReady = true;
      input.focus();
      input.select();
    }, 100);
    let isFinished = false;
    const finishEdit = async (cancelled) => {
      if (isFinished)
        return;
      isFinished = true;
      card.removeClass("is-editing");
      if (!cancelled) {
        const newTitle = input.value.trim() || "New Task";
        entry.title = newTitle;
        await this.callbacks.onEntryUpdate(entry);
      }
      content.innerHTML = `
        <div class="fcp-entry-title">${this.escapeHtml(entry.title || "Untitled")}</div>
        <div class="fcp-entry-time">${entry.startTime} - ${entry.endTime}</div>
      `;
    };
    input.addEventListener("blur", () => {
      if (!isReady)
        return;
      finishEdit(false);
    });
    input.addEventListener("keydown", (e) => {
      e.stopPropagation();
      if (e.key === "Enter") {
        e.preventDefault();
        finishEdit(false);
      } else if (e.key === "Escape") {
        e.preventDefault();
        finishEdit(true);
      }
    });
    input.addEventListener("keyup", (e) => e.stopPropagation());
    input.addEventListener("keypress", (e) => e.stopPropagation());
    input.addEventListener("mousedown", (e) => e.stopPropagation());
    input.addEventListener("mouseup", (e) => e.stopPropagation());
    input.addEventListener("click", (e) => e.stopPropagation());
    input.addEventListener("dblclick", (e) => e.stopPropagation());
  }
  setupCardDrag(card, entry) {
    let isDragging = false;
    let hasMoved = false;
    let dragMode = "move";
    let startY = 0;
    let startTop = 0;
    let startHeight = 0;
    const maxGridHeight = this.totalHours * this.hourHeight;
    const onMouseDown = (e) => {
      if (e.button !== 0 || card.classList.contains("is-editing"))
        return;
      const target = e.target;
      if (target.classList.contains("top")) {
        dragMode = "resize-top";
      } else if (target.classList.contains("bottom")) {
        dragMode = "resize-bottom";
      } else {
        dragMode = "move";
      }
      isDragging = true;
      hasMoved = false;
      startY = e.clientY;
      startTop = parseFloat(card.style.top) || 0;
      startHeight = parseFloat(card.style.height) || this.slotHeight;
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    };
    const onMouseMove = (e) => {
      if (!isDragging)
        return;
      const deltaY = e.clientY - startY;
      if (Math.abs(deltaY) > 3) {
        hasMoved = true;
        card.addClass("is-dragging");
      }
      const columnsContainer = this.containerEl.querySelector(".fcp-columns-container");
      if (dragMode === "move") {
        const rawTop = startTop + deltaY;
        const snappedTop = Math.max(0, Math.min(Math.round(rawTop / this.slotHeight) * this.slotHeight, maxGridHeight - startHeight));
        card.style.top = `${snappedTop}px`;
        if (columnsContainer) {
          const rect = columnsContainer.getBoundingClientRect();
          const colWidth = rect.width / 7;
          const relX = e.clientX - rect.left;
          const targetColIndex = Math.max(0, Math.min(6, Math.floor(relX / colWidth)));
          const targetColEl = columnsContainer.querySelector(`.fcp-day-column[data-col-index="${targetColIndex}"]`);
          if (targetColEl && card.parentElement !== targetColEl) {
            targetColEl.appendChild(card);
            hasMoved = true;
          }
        }
      } else if (dragMode === "resize-top") {
        const rawTop = startTop + deltaY;
        const snappedTop = Math.max(0, Math.min(Math.round(rawTop / this.slotHeight) * this.slotHeight, startTop + startHeight - this.slotHeight));
        const snappedHeight = startHeight + (startTop - snappedTop);
        card.style.top = `${snappedTop}px`;
        card.style.height = `${snappedHeight}px`;
      } else if (dragMode === "resize-bottom") {
        const rawHeight = startHeight + deltaY;
        const snappedHeight = Math.max(this.slotHeight, Math.min(Math.round(rawHeight / this.slotHeight) * this.slotHeight, maxGridHeight - startTop));
        card.style.height = `${snappedHeight}px`;
      }
      if (hasMoved) {
        const currentTop = parseFloat(card.style.top) || 0;
        const currentHeight = parseFloat(card.style.height) || this.slotHeight;
        if (currentHeight <= this.slotHeight) {
          card.addClass("is-short");
        } else {
          card.removeClass("is-short");
        }
        const startMins = this.startHour * 60 + Math.round(currentTop / this.slotHeight) * 30;
        const endMins = startMins + Math.round(currentHeight / this.slotHeight) * 30;
        const timeDiv = card.querySelector(".fcp-entry-time");
        if (timeDiv) {
          timeDiv.textContent = `${this.minutesToTimeStr(startMins)} - ${this.minutesToTimeStr(endMins)}`;
        }
      }
    };
    const onMouseUp = async (e) => {
      if (!isDragging)
        return;
      isDragging = false;
      card.removeClass("is-dragging");
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      if (!hasMoved)
        return;
      const finalTop = parseFloat(card.style.top) || 0;
      const finalHeight = parseFloat(card.style.height) || this.slotHeight;
      const startSlot = Math.round(finalTop / this.slotHeight);
      const durationSlots = Math.max(1, Math.round(finalHeight / this.slotHeight));
      const startMins = this.startHour * 60 + startSlot * 30;
      const endMins = Math.min(this.endHour * 60, startMins + durationSlots * 30);
      const targetColEl = card.closest(".fcp-day-column");
      if (targetColEl && targetColEl.dataset.date) {
        entry.date = targetColEl.dataset.date;
      }
      entry.startTime = this.minutesToTimeStr(startMins);
      entry.endTime = this.minutesToTimeStr(endMins);
      await this.callbacks.onEntryUpdate(entry);
    };
    card.addEventListener("mousedown", onMouseDown);
  }
  formatDateIso(d) {
    const y = d.getFullYear();
    const m = (d.getMonth() + 1).toString().padStart(2, "0");
    const day = d.getDate().toString().padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
  timeStrToMinutes(str) {
    if (!str)
      return 0;
    const parts = str.split(":").map(Number);
    return (parts[0] || 0) * 60 + (parts[1] || 0);
  }
  minutesToTimeStr(mins) {
    const h = Math.floor(mins / 60);
    const m = mins % 60;
    return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}`;
  }
  snapTo30Min(mins) {
    return Math.round(mins / 30) * 30;
  }
  escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }
};

// src/views/MonthViewRender.ts
var MonthViewRenderComponent = class {
  constructor(containerEl, year, month, entries, pomoLogs, dailyHoursMap, callbacks) {
    this.containerEl = containerEl;
    this.currentYear = year;
    this.currentMonth = month;
    this.entries = entries;
    this.pomoLogs = pomoLogs;
    this.dailyHoursMap = dailyHoursMap;
    this.callbacks = callbacks;
    this.render();
  }
  update(year, month, entries, pomoLogs, dailyHoursMap) {
    this.currentYear = year;
    this.currentMonth = month;
    this.entries = entries;
    this.pomoLogs = pomoLogs;
    this.dailyHoursMap = dailyHoursMap;
    this.render();
  }
  getTaskColor(title) {
    const normalized = title.toLowerCase().trim();
    let hash = 0;
    for (let i = 0; i < normalized.length; i++) {
      hash = normalized.charCodeAt(i) + ((hash << 5) - hash);
    }
    const hue = Math.abs(hash) % 360;
    return `hsl(${hue}, 68%, 52%)`;
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("fcp-month-view-wrapper");
    const layoutContainer = this.containerEl.createDiv("fcp-month-layout-container");
    const gridPanel = layoutContainer.createDiv("fcp-month-grid-panel");
    const weekdaysHeader = gridPanel.createDiv("fcp-month-weekdays-header");
    const dayNames = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
    dayNames.forEach((d) => {
      const col = weekdaysHeader.createDiv("fcp-month-weekday-col");
      col.textContent = d;
    });
    const monthGrid = gridPanel.createDiv("fcp-month-grid");
    const firstDayDate = new Date(this.currentYear, this.currentMonth, 1);
    let startDayOfWeek = firstDayDate.getDay() - 1;
    if (startDayOfWeek === -1)
      startDayOfWeek = 6;
    const daysInMonth = new Date(this.currentYear, this.currentMonth + 1, 0).getDate();
    const daysInPrevMonth = new Date(this.currentYear, this.currentMonth, 0).getDate();
    const totalCells = Math.ceil((startDayOfWeek + daysInMonth) / 7) * 7;
    const todayIso = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    for (let i = 0; i < totalCells; i++) {
      let dayNumber;
      let monthOffset = 0;
      if (i < startDayOfWeek) {
        dayNumber = daysInPrevMonth - startDayOfWeek + i + 1;
        monthOffset = -1;
      } else if (i >= startDayOfWeek + daysInMonth) {
        dayNumber = i - (startDayOfWeek + daysInMonth) + 1;
        monthOffset = 1;
      } else {
        dayNumber = i - startDayOfWeek + 1;
        monthOffset = 0;
      }
      const cellYear = this.currentYear + (this.currentMonth + monthOffset < 0 ? -1 : this.currentMonth + monthOffset > 11 ? 1 : 0);
      const cellMonth = (this.currentMonth + monthOffset + 12) % 12;
      const cellIso = `${cellYear}-${(cellMonth + 1).toString().padStart(2, "0")}-${dayNumber.toString().padStart(2, "0")}`;
      const isToday = cellIso === todayIso;
      const isOtherMonth = monthOffset !== 0;
      const cellEl = monthGrid.createDiv(`fcp-month-cell ${isOtherMonth ? "other-month" : ""} ${isToday ? "is-today" : ""}`);
      const dailyHours = this.dailyHoursMap.get(cellIso) || 0;
      if (dailyHours > 0) {
        const intensity = Math.min(1, dailyHours / 8);
        const alpha = 0.12 + intensity * 0.58;
        cellEl.style.backgroundColor = `rgba(59, 130, 246, ${alpha.toFixed(2)})`;
        cellEl.style.borderColor = `rgba(59, 130, 246, ${(alpha + 0.2).toFixed(2)})`;
      }
      const cellHeader = cellEl.createDiv("fcp-month-cell-header");
      cellHeader.textContent = dayNumber.toString();
      cellEl.addEventListener("click", (e) => {
        if (e.target.closest(".fcp-month-event-item"))
          return;
        this.callbacks.onDayClick(cellIso);
      });
      const dayEvents = this.entries.filter((e) => e.date === cellIso && e.type === "event");
      if (dayEvents.length > 0) {
        const eventsContainer = cellEl.createDiv("fcp-month-events-container");
        dayEvents.forEach((evt) => {
          const evtEl = eventsContainer.createDiv("fcp-month-event-item");
          evtEl.innerHTML = `
            <span class="fcp-evt-dot"></span>
            <span class="fcp-evt-title">${this.escapeHtml(evt.title || "Event")}</span>
          `;
          evtEl.addEventListener("click", (e) => {
            e.stopPropagation();
            this.callbacks.onEventClick(evt);
          });
        });
      }
      if (dailyHours > 0) {
        const hoursTag = cellEl.createDiv("fcp-month-day-hours");
        const formattedHours = dailyHours % 1 === 0 ? `${dailyHours} Hrs` : `${dailyHours.toFixed(1)} Hrs`;
        hoursTag.textContent = formattedHours;
      }
    }
    this.renderBreakdownPanel(layoutContainer);
    setTimeout(() => {
      const scrollbarWidth = monthGrid.offsetWidth - monthGrid.clientWidth;
      if (scrollbarWidth > 0) {
        weekdaysHeader.style.paddingRight = `${scrollbarWidth}px`;
      } else {
        weekdaysHeader.style.paddingRight = "0px";
      }
    }, 0);
  }
  renderBreakdownPanel(parentEl) {
    const monthPrefix = `${this.currentYear}-${(this.currentMonth + 1).toString().padStart(2, "0")}`;
    const activityMap = /* @__PURE__ */ new Map();
    let grandTotalSeconds = 0;
    this.pomoLogs.forEach((log) => {
      if (log.type !== "work" || !log.date || !log.date.startsWith(monthPrefix))
        return;
      const title = (log.taskTitle || "General Focus").trim();
      const normKey = title.toLowerCase();
      const secs = log.durationSeconds || 0;
      if (secs <= 0)
        return;
      grandTotalSeconds += secs;
      if (activityMap.has(normKey)) {
        activityMap.get(normKey).totalSeconds += secs;
      } else {
        activityMap.set(normKey, {
          displayTitle: title,
          totalSeconds: secs,
          color: this.getTaskColor(title)
        });
      }
    });
    const grandTotalHours = grandTotalSeconds / 3600;
    const activities = Array.from(activityMap.values()).map((act) => ({
      displayTitle: act.displayTitle,
      totalHours: act.totalSeconds / 3600,
      color: act.color
    })).sort((a, b) => b.totalHours - a.totalHours);
    const breakdownPanel = parentEl.createDiv("fcp-month-breakdown-panel");
    const header = breakdownPanel.createDiv("fcp-breakdown-header");
    header.innerHTML = `
      <div class="fcp-breakdown-title">Actual Focus Time</div>
      <div class="fcp-breakdown-subtitle">${grandTotalHours.toFixed(1)} Total Focus Hrs</div>
    `;
    if (activities.length === 0 || grandTotalSeconds === 0) {
      const emptyMsg = breakdownPanel.createDiv("fcp-breakdown-empty");
      emptyMsg.textContent = "No actual focus time recorded this month.";
      return;
    }
    const barContainer = breakdownPanel.createDiv("fcp-stacked-bar");
    activities.forEach((act) => {
      const pct = act.totalHours / (grandTotalHours || 1) * 100;
      const segment = barContainer.createDiv("fcp-stacked-segment");
      segment.style.backgroundColor = act.color;
      segment.style.flex = `${pct}`;
      segment.title = `${act.displayTitle}: ${act.totalHours.toFixed(1)}h (${pct.toFixed(0)}%)`;
    });
    const legend = breakdownPanel.createDiv("fcp-breakdown-legend");
    activities.forEach((act) => {
      const pct = act.totalHours / (grandTotalHours || 1) * 100;
      const item = legend.createDiv("fcp-legend-item");
      item.innerHTML = `
        <div class="fcp-legend-left">
          <span class="fcp-legend-dot" style="background-color: ${act.color};"></span>
          <span class="fcp-legend-name" title="${this.escapeHtml(act.displayTitle)}">${this.escapeHtml(act.displayTitle)}</span>
        </div>
        <div class="fcp-legend-right">
          <span class="fcp-legend-hours">${act.totalHours.toFixed(1)}h</span>
          <span class="fcp-legend-pct">${pct.toFixed(0)}%</span>
        </div>
      `;
    });
  }
  escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }
};

// src/views/CalendarView.ts
var VIEW_TYPE_FOCUS_CALENDAR = "focus-calendar-pomodoro-view";
var FocusCalendarView = class extends import_obsidian3.ItemView {
  constructor(leaf, storage, pomodoro) {
    super(leaf);
    this.viewMode = "week";
    this.currentDate = /* @__PURE__ */ new Date();
    this.headerComponent = null;
    this.weekComponent = null;
    this.monthComponent = null;
    this.entries = [];
    this.pomoLogs = [];
    this.storage = storage;
    this.pomodoro = pomodoro;
  }
  getViewType() {
    return VIEW_TYPE_FOCUS_CALENDAR;
  }
  getDisplayText() {
    return "Focus Calendar & Pomodoro";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    await this.refreshData();
    this.renderView();
  }
  async refreshData() {
    const yearMonth = this.getYearMonthString(this.currentDate);
    this.entries = await this.storage.loadEntriesForMonth(yearMonth);
    this.pomoLogs = await this.storage.loadPomodoroLogsForMonth(yearMonth);
  }
  renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("fcp-main-container");
    const navBar = container.createDiv("fcp-nav-bar");
    const leftNav = navBar.createDiv("fcp-nav-left");
    const todayBtn = leftNav.createEl("button", { cls: "fcp-btn", text: "Today" });
    todayBtn.onclick = async () => {
      this.currentDate = /* @__PURE__ */ new Date();
      await this.refreshData();
      this.renderView();
    };
    const prevBtn = leftNav.createEl("button", { cls: "fcp-icon-btn", ariaLabel: "Previous" });
    prevBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>`;
    prevBtn.onclick = async () => {
      if (this.viewMode === "week") {
        this.currentDate.setDate(this.currentDate.getDate() - 7);
      } else {
        this.currentDate.setMonth(this.currentDate.getMonth() - 1);
      }
      await this.refreshData();
      this.renderView();
    };
    const nextBtn = leftNav.createEl("button", { cls: "fcp-icon-btn", ariaLabel: "Next" });
    nextBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>`;
    nextBtn.onclick = async () => {
      if (this.viewMode === "week") {
        this.currentDate.setDate(this.currentDate.getDate() + 7);
      } else {
        this.currentDate.setMonth(this.currentDate.getMonth() + 1);
      }
      await this.refreshData();
      this.renderView();
    };
    const dateTitle = leftNav.createDiv("fcp-nav-date-title");
    dateTitle.textContent = this.currentDate.toLocaleDateString("en-US", { month: "long", year: "numeric" });
    const modeSwitch = navBar.createDiv("fcp-mode-switch");
    const weekBtn = modeSwitch.createEl("button", {
      cls: `fcp-switch-btn ${this.viewMode === "week" ? "active" : ""}`,
      text: "Week"
    });
    weekBtn.onclick = () => {
      if (this.viewMode !== "week") {
        this.viewMode = "week";
        this.renderView();
      }
    };
    const monthBtn = modeSwitch.createEl("button", {
      cls: `fcp-switch-btn ${this.viewMode === "month" ? "active" : ""}`,
      text: "Month"
    });
    monthBtn.onclick = () => {
      if (this.viewMode !== "month") {
        this.viewMode = "month";
        this.renderView();
      }
    };
    const pomoHeaderContainer = container.createDiv("fcp-header-slot");
    const totalHours = this.calculateTotalHours();
    const imminentEvent = this.getImminentEvent();
    this.headerComponent = new PomodoroHeaderComponent(
      pomoHeaderContainer,
      this.pomodoro,
      this.viewMode,
      totalHours,
      imminentEvent
    );
    const viewAreaContainer = container.createDiv("fcp-view-area");
    if (this.viewMode === "week") {
      const weekStart = this.getMondayOfWeek(this.currentDate);
      this.weekComponent = new WeekViewRenderComponent(
        viewAreaContainer,
        weekStart,
        this.entries,
        {
          onEntryCreate: async (date, startTime, endTime) => {
            const newEntry = {
              id: "entry-" + Date.now(),
              title: "",
              date,
              startTime,
              endTime,
              type: "task",
              createdAt: Date.now(),
              updatedAt: Date.now()
            };
            this.entries.push(newEntry);
            await this.storage.saveEntry(newEntry);
            return newEntry;
          },
          onEntryUpdate: async (entry) => {
            entry.updatedAt = Date.now();
            await this.storage.saveEntry(entry);
            this.updateHeaderStats();
          },
          onEntryDelete: async (entry) => {
            var _a;
            await this.storage.deleteEntry(entry.id, entry.date);
            this.entries = this.entries.filter((e) => e.id !== entry.id);
            if (((_a = this.pomodoro.getFocusedTask()) == null ? void 0 : _a.id) === entry.id) {
              this.pomodoro.setFocusedTask(null);
            }
            this.updateHeaderStats();
          },
          onTaskFocus: (entry) => {
            this.pomodoro.setFocusedTask(entry);
          },
          getFocusedTaskId: () => {
            var _a;
            return (_a = this.pomodoro.getFocusedTask()) == null ? void 0 : _a.id;
          }
        }
      );
    } else {
      this.monthComponent = new MonthViewRenderComponent(
        viewAreaContainer,
        this.currentDate.getFullYear(),
        this.currentDate.getMonth(),
        this.entries,
        this.pomoLogs,
        this.buildDailyHoursMap(),
        {
          onDayClick: async (dateIso) => {
            this.currentDate = /* @__PURE__ */ new Date(dateIso + "T12:00:00");
            this.viewMode = "week";
            await this.refreshData();
            this.renderView();
          },
          onEventClick: (entry) => {
          }
        }
      );
    }
  }
  updateHeaderStats() {
    if (this.headerComponent) {
      this.headerComponent.update(this.viewMode, this.calculateTotalHours(), this.getImminentEvent());
    }
  }
  getImminentEvent() {
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    const todayTime = (/* @__PURE__ */ new Date(todayStr + "T00:00:00")).getTime();
    const futureEvents = this.entries.filter((e) => e.type === "event" && e.date >= todayStr);
    if (futureEvents.length === 0)
      return null;
    futureEvents.sort((a, b) => a.date.localeCompare(b.date));
    const closest = futureEvents[0];
    const eventTime = (/* @__PURE__ */ new Date(closest.date + "T00:00:00")).getTime();
    const diffDays = Math.round((eventTime - todayTime) / (1e3 * 60 * 60 * 24));
    return {
      title: closest.title || "Untitled Event",
      daysAway: Math.max(0, diffDays)
    };
  }
  buildDailyHoursMap() {
    const map = /* @__PURE__ */ new Map();
    this.pomoLogs.forEach((log) => {
      if (log.type === "work" && log.date) {
        const current = map.get(log.date) || 0;
        map.set(log.date, current + log.durationSeconds / 3600);
      }
    });
    return map;
  }
  calculateTotalHours() {
    let totalSeconds = 0;
    if (this.viewMode === "week") {
      const weekStart = this.getMondayOfWeek(this.currentDate);
      const weekEnd = new Date(weekStart);
      weekEnd.setDate(weekEnd.getDate() + 7);
      const weekStartIso = weekStart.toISOString().substring(0, 10);
      const weekEndIso = weekEnd.toISOString().substring(0, 10);
      this.pomoLogs.forEach((log) => {
        if (log.type === "work" && log.date >= weekStartIso && log.date < weekEndIso) {
          totalSeconds += log.durationSeconds;
        }
      });
    } else {
      this.pomoLogs.forEach((log) => {
        if (log.type === "work") {
          totalSeconds += log.durationSeconds;
        }
      });
    }
    return totalSeconds / 3600;
  }
  getMondayOfWeek(d) {
    const date = new Date(d);
    const day = date.getDay();
    const diff = date.getDate() - day + (day === 0 ? -6 : 1);
    return new Date(date.setDate(diff));
  }
  getYearMonthString(d) {
    const y = d.getFullYear();
    const m = (d.getMonth() + 1).toString().padStart(2, "0");
    return `${y}-${m}`;
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var FocusCalendarSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Focus Calendar & Pomodoro Settings" });
    new import_obsidian4.Setting(containerEl).setName("Work Duration (minutes)").setDesc("Length of work pomodoro sessions in minutes.").addText((text) => text.setPlaceholder("40").setValue(this.plugin.settings.workDurationMinutes.toString()).onChange(async (value) => {
      const val = parseInt(value, 10);
      if (!isNaN(val) && val > 0) {
        this.plugin.settings.workDurationMinutes = val;
        await this.plugin.saveSettings();
        this.plugin.pomodoro.notifySettingsUpdated();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("Break Duration (minutes)").setDesc("Length of break pomodoro sessions in minutes.").addText((text) => text.setPlaceholder("10").setValue(this.plugin.settings.breakDurationMinutes.toString()).onChange(async (value) => {
      const val = parseInt(value, 10);
      if (!isNaN(val) && val > 0) {
        this.plugin.settings.breakDurationMinutes = val;
        await this.plugin.saveSettings();
        this.plugin.pomodoro.notifySettingsUpdated();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("Completion Alarm Sound (Vault MP3 Path)").setDesc("Path to an MP3 file in your vault (e.g. Sounds/bell.mp3). Leave blank for no sound.").addText((text) => text.setPlaceholder("Sounds/bell.mp3").setValue(this.plugin.settings.soundFilePath || "").onChange(async (value) => {
      this.plugin.settings.soundFilePath = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Data Storage Directory").setDesc("Folder path in your vault where calendar JSON data files are saved.").addText((text) => text.setPlaceholder("CalendarData").setValue(this.plugin.settings.dataDirectory).onChange(async (value) => {
      this.plugin.settings.dataDirectory = value.trim() || "CalendarData";
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Auto-Start Break").setDesc("Automatically start break timer when a work pomodoro session completes.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoStartBreak).onChange(async (value) => {
      this.plugin.settings.autoStartBreak = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/main.ts
var FocusCalendarPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.isAutoStarted = false;
  }
  async onload() {
    await this.loadSettings();
    this.storage = new StorageManager(this.app, () => this.settings);
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("focus-calendar-status-bar");
    this.statusBarItem.style.cursor = "pointer";
    this.statusBarItem.addEventListener("click", () => {
      this.pomodoro.togglePlayPause();
    });
    this.pomodoro = new PomodoroManager(
      () => this.settings,
      (state) => {
        this.updateStatusBar(state);
        this.app.workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR).forEach((leaf) => {
          if (leaf.view instanceof FocusCalendarView) {
            leaf.view.updateHeaderStats();
          }
        });
      },
      async (session) => {
        await this.storage.logPomodoroSession(session);
        this.app.workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR).forEach((leaf) => {
          if (leaf.view instanceof FocusCalendarView) {
            leaf.view.refreshData().then(() => leaf.view.renderView());
          }
        });
      },
      (filePath) => this.playVaultAudio(filePath),
      () => this.app.workspace.trigger("focus-calendar:break-start")
    );
    this.updateStatusBar(this.pomodoro.getState());
    this.registerView(
      VIEW_TYPE_FOCUS_CALENDAR,
      (leaf) => new FocusCalendarView(leaf, this.storage, this.pomodoro)
    );
    this.addRibbonIcon("calendar-clock", "Open Focus Calendar & Pomodoro", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-focus-calendar-view",
      name: "Open Focus Calendar & Pomodoro View",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new FocusCalendarSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("omnirecall:drill-complete", async (data) => {
        const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
        await this.storage.logPomodoroSession({
          id: "drill-" + Date.now(),
          taskTitle: `[Drill] ${data.title || "Exercise"}`,
          type: "work",
          durationSeconds: data.timeSec || 0,
          completedAt: Date.now(),
          date: today
        });
      })
    );
    this.registerEvent(
      this.app.workspace.on("omnirecall:review-complete", async (data) => {
        const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
        await this.storage.logPomodoroSession({
          id: "review-" + Date.now(),
          taskTitle: `[Flashcards] ${data.title || "Review Queue"}`,
          type: "work",
          durationSeconds: data.timeSec || 0,
          completedAt: Date.now(),
          date: today
        });
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.storage && this.storage.isLocalSaving)
          return;
        if (file.path.startsWith(this.settings.dataDirectory) && file.path.endsWith(".json")) {
          this.app.workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR).forEach((leaf) => {
            if (leaf.view instanceof FocusCalendarView) {
              leaf.view.refreshData().then(() => leaf.view.renderView());
            }
          });
        }
      })
    );
  }
  updateStatusBar(state) {
    if (!this.statusBarItem)
      return;
    const mins = Math.floor(state.timeLeftSeconds / 60);
    const secs = state.timeLeftSeconds % 60;
    const timeFormatted = `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
    const taskTitle = state.focusedTask ? state.focusedTask.title : state.mode.toUpperCase();
    const statusIcon = state.isRunning ? "\u23F1\uFE0F" : "\u23F8\uFE0F";
    this.statusBarItem.setText(`${statusIcon} ${timeFormatted} [${taskTitle}]`);
  }
  startAutoStudySession(title) {
    const state = this.pomodoro.getState();
    if (state.isRunning) {
      return false;
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    this.pomodoro.setFocusedTask({
      id: "auto-" + Date.now(),
      title,
      date: today,
      time: (/* @__PURE__ */ new Date()).toTimeString().substring(0, 5),
      durationMinutes: 40,
      category: "Study",
      completed: false
    });
    this.isAutoStarted = true;
    this.pomodoro.start();
    return true;
  }
  endAutoStudySession() {
    if (this.isAutoStarted) {
      this.pomodoro.pause();
      this.isAutoStarted = false;
    }
  }
  async playVaultAudio(filePath) {
    try {
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian5.TFile) {
        const resourcePath = this.app.vault.getResourcePath(file);
        const audio = new Audio(resourcePath);
        await audio.play();
      } else {
        console.warn(`Focus Calendar: Sound file not found at path: ${filePath}`);
      }
    } catch (err) {
      console.error("Focus Calendar: Failed to play audio file from vault", err);
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_FOCUS_CALENDAR,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  onunload() {
    this.pomodoro.pause();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
