/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FocusCalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/views/CalendarView.ts
var import_obsidian2 = require("obsidian");

// src/views/PomodoroHeader.ts
var PomodoroHeaderComponent = class {
  constructor(containerEl, pomodoroManager, viewMode, totalHours, imminentEvent = null) {
    this.containerEl = containerEl;
    this.pomodoroManager = pomodoroManager;
    this.viewMode = viewMode;
    this.totalHours = totalHours;
    this.imminentEvent = imminentEvent;
    this.render();
  }
  update(viewMode, totalHours, imminentEvent = null) {
    this.viewMode = viewMode;
    this.totalHours = totalHours;
    this.imminentEvent = imminentEvent;
    this.render();
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("fcp-pomodoro-header");
    if (this.viewMode === "month") {
      this.containerEl.addClass("month-mode");
      this.renderMonthHeader();
    } else {
      this.containerEl.removeClass("month-mode");
      this.renderWeekHeader();
    }
  }
  renderMonthHeader() {
    const leftDiv = this.containerEl.createDiv("fcp-pomo-left-imminent");
    if (this.imminentEvent) {
      let daysStr = "";
      if (this.imminentEvent.daysAway === 0) {
        daysStr = "today";
      } else if (this.imminentEvent.daysAway === 1) {
        daysStr = "1 day away";
      } else {
        daysStr = `${this.imminentEvent.daysAway} days away`;
      }
      leftDiv.innerHTML = `
        <span class="fcp-imminent-badge">UPCOMING EVENT</span>
        <span class="fcp-imminent-text"><strong>${this.escapeHtml(this.imminentEvent.title)}</strong> is ${daysStr}</span>
      `;
    } else {
      leftDiv.innerHTML = `<span class="fcp-imminent-text muted">No upcoming events</span>`;
    }
    const rightSection = this.containerEl.createDiv("fcp-pomo-right");
    const hoursCard = rightSection.createDiv("fcp-hours-card");
    hoursCard.innerHTML = `
      <div class="fcp-hours-val">${this.totalHours.toFixed(1)} <span class="fcp-hours-unit">HRS</span></div>
      <div class="fcp-hours-sub">THIS MONTH</div>
    `;
  }
  renderWeekHeader() {
    var _a, _b;
    const state = this.pomodoroManager.getState();
    const isWork = state.mode === "work";
    const accentColor = isWork ? "var(--fcp-red-accent, #ef4444)" : "var(--fcp-blue-accent, #3b82f6)";
    const focusedTitle = (_b = (_a = state.focusedTask) == null ? void 0 : _a.title) == null ? void 0 : _b.trim();
    const modeLabel = isWork ? focusedTitle ? focusedTitle : "WORK" : "BREAK";
    this.containerEl.createDiv("fcp-pomo-left-spacer");
    const centerSection = this.containerEl.createDiv("fcp-pomo-center");
    const svgSize = 64;
    const strokeWidth = 5;
    const radius = (svgSize - strokeWidth) / 2;
    const circumference = 2 * Math.PI * radius;
    const progressRatio = state.totalDurationSeconds > 0 ? state.timeLeftSeconds / state.totalDurationSeconds : 0;
    const strokeDashoffset = circumference * (1 - progressRatio);
    const minutes = Math.floor(state.timeLeftSeconds / 60);
    const seconds = state.timeLeftSeconds % 60;
    const formattedTime = `${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`;
    const svgWrapper = centerSection.createDiv("fcp-radial-wrapper");
    svgWrapper.style.setProperty("--accent-color", accentColor);
    svgWrapper.innerHTML = `
      <svg width="${svgSize}" height="${svgSize}" viewBox="0 0 ${svgSize} ${svgSize}" class="fcp-radial-svg">
        <circle
          cx="${svgSize / 2}" cy="${svgSize / 2}" r="${radius}"
          fill="none" stroke="var(--background-modifier-border)" stroke-width="${strokeWidth}"
        />
        <circle
          cx="${svgSize / 2}" cy="${svgSize / 2}" r="${radius}"
          fill="none" stroke="${accentColor}" stroke-width="${strokeWidth}"
          stroke-linecap="round"
          stroke-dasharray="${circumference}"
          stroke-dashoffset="${strokeDashoffset}"
          transform="rotate(-90 ${svgSize / 2} ${svgSize / 2})"
          style="transition: stroke-dashoffset 0.3s ease, stroke 0.3s ease;"
        />
      </svg>
      <div class="fcp-radial-text">${formattedTime}</div>
    `;
    const controlsDiv = centerSection.createDiv("fcp-pomo-controls");
    const modeBadge = controlsDiv.createDiv("fcp-mode-badge");
    modeBadge.textContent = modeLabel;
    modeBadge.setAttribute("title", modeLabel);
    modeBadge.style.color = accentColor;
    modeBadge.style.borderColor = accentColor;
    const btnGroup = controlsDiv.createDiv("fcp-btn-group");
    const playPauseBtn = btnGroup.createEl("button", {
      cls: "fcp-icon-btn fcp-play-btn",
      ariaLabel: state.isRunning ? "Pause" : "Start"
    });
    playPauseBtn.innerHTML = state.isRunning ? `<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>` : `<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>`;
    playPauseBtn.onclick = () => this.pomodoroManager.togglePlayPause();
    const resetBtn = btnGroup.createEl("button", {
      cls: "fcp-icon-btn",
      ariaLabel: "Reset"
    });
    resetBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>`;
    resetBtn.onclick = () => this.pomodoroManager.resetTimer();
    const skipBtn = btnGroup.createEl("button", {
      cls: "fcp-icon-btn",
      ariaLabel: "Switch Mode"
    });
    skipBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="5 4 15 12 5 20 5 4"/><line x1="19" y1="5" x2="19" y2="19"/></svg>`;
    skipBtn.onclick = () => this.pomodoroManager.switchMode();
    const rightSection = this.containerEl.createDiv("fcp-pomo-right");
    const hoursCard = rightSection.createDiv("fcp-hours-card");
    hoursCard.innerHTML = `
      <div class="fcp-hours-val">${this.totalHours.toFixed(1)} <span class="fcp-hours-unit">HRS</span></div>
      <div class="fcp-hours-sub">THIS WEEK</div>
    `;
  }
  escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }
};

// src/views/WeekViewRender.ts
var import_obsidian = require("obsidian");
var TaskEditModal = class extends import_obsidian.Modal {
  constructor(app, entry, onSave, onDelete) {
    super(app);
    this.entry = entry;
    this.onSave = onSave;
    this.onDelete = onDelete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("fcp-edit-modal");
    contentEl.createEl("h2", { text: this.entry.title ? "Edit Task / Event" : "New Task / Event" });
    let titleVal = this.entry.title || "";
    let descVal = this.entry.description || "";
    let typeVal = this.entry.type || "task";
    let startTimeVal = this.entry.startTime || "09:00";
    let endTimeVal = this.entry.endTime || "10:00";
    new import_obsidian.Setting(contentEl).setName("Title").setDesc("Title of the task or event.").addText((text) => text.setPlaceholder("Enter title...").setValue(titleVal).onChange((v) => {
      titleVal = v;
    }));
    new import_obsidian.Setting(contentEl).setName("Description").setDesc("Optional notes or description.").addTextArea((text) => {
      text.setPlaceholder("Enter description / notes...").setValue(descVal).onChange((v) => {
        descVal = v;
      });
      text.inputEl.rows = 4;
      text.inputEl.style.width = "100%";
      text.inputEl.style.resize = "vertical";
    });
    new import_obsidian.Setting(contentEl).setName("Type").setDesc("Task (Pastel Blue) or Event (Green).").addDropdown((drop) => drop.addOption("task", "Task (Pastel Blue)").addOption("event", "Event (Green)").setValue(typeVal).onChange((v) => {
      typeVal = v;
    }));
    new import_obsidian.Setting(contentEl).setName("Time Range").setDesc("Start and End time (HH:mm).").addText((text) => text.setPlaceholder("09:00").setValue(startTimeVal).onChange((v) => {
      startTimeVal = v;
    })).addText((text) => text.setPlaceholder("10:00").setValue(endTimeVal).onChange((v) => {
      endTimeVal = v;
    }));
    const buttonRow = contentEl.createDiv("fcp-modal-button-row");
    const deleteBtn = buttonRow.createEl("button", {
      cls: "mod-warning fcp-modal-delete-btn",
      text: "Delete"
    });
    deleteBtn.onclick = async () => {
      this.close();
      await this.onDelete(this.entry);
    };
    const rightBtns = buttonRow.createDiv("fcp-modal-right-btns");
    const cancelBtn = rightBtns.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => {
      this.close();
    };
    const saveBtn = rightBtns.createEl("button", {
      cls: "mod-cta",
      text: "Save"
    });
    saveBtn.onclick = async () => {
      this.entry.title = titleVal.trim() || "Untitled";
      this.entry.description = descVal.trim() || void 0;
      this.entry.type = typeVal;
      this.entry.startTime = startTimeVal.trim() || this.entry.startTime;
      this.entry.endTime = endTimeVal.trim() || this.entry.endTime;
      this.close();
      await this.onSave(this.entry);
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WeekViewRenderComponent = class {
  // pixels per 30 minutes (52 / 2)
  constructor(app, containerEl, weekStart, entries, callbacks) {
    // Constants for 30-minute precision snapping
    this.startHour = 5;
    // 05:00
    this.endHour = 24;
    // 24:00
    this.totalHours = 19;
    // 5..24
    this.hourHeight = 52;
    // pixels per hour
    this.slotHeight = 26;
    this.app = app;
    this.containerEl = containerEl;
    this.weekStart = weekStart;
    this.entries = entries;
    this.callbacks = callbacks;
    this.render();
  }
  update(weekStart, entries) {
    this.weekStart = weekStart;
    this.entries = entries;
    this.render();
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("fcp-week-view-wrapper");
    const weekDates = [];
    for (let i = 0; i < 7; i++) {
      const d = new Date(this.weekStart);
      d.setDate(d.getDate() + i);
      weekDates.push(d);
    }
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    const headerRow = this.containerEl.createDiv("fcp-week-header");
    headerRow.createDiv("fcp-time-gutter-header");
    const daysHeaderGrid = headerRow.createDiv("fcp-week-days-header-grid");
    weekDates.forEach((date) => {
      const dateStr = this.formatDateIso(date);
      const isToday = dateStr === todayStr;
      const dayColHeader = daysHeaderGrid.createDiv(`fcp-day-header-cell ${isToday ? "is-today" : ""}`);
      const dayName = date.toLocaleDateString("en-US", { weekday: "short" });
      const dayNum = date.getDate();
      dayColHeader.innerHTML = `
        <div class="fcp-day-name">${dayName}</div>
        <div class="fcp-day-num">${dayNum}</div>
      `;
    });
    const gridBody = this.containerEl.createDiv("fcp-week-grid-body");
    const timeGutter = gridBody.createDiv("fcp-time-gutter");
    for (let h = this.startHour; h <= this.endHour; h++) {
      const timeLabel = timeGutter.createDiv("fcp-time-label");
      timeLabel.style.height = `${this.hourHeight}px`;
      const hourStr = h < 24 ? `${h.toString().padStart(2, "0")}:00` : "24:00";
      timeLabel.textContent = hourStr;
    }
    const columnsContainer = gridBody.createDiv("fcp-columns-container");
    columnsContainer.style.height = `${this.totalHours * this.hourHeight}px`;
    const gridLines = columnsContainer.createDiv("fcp-grid-lines");
    for (let h = 0; h < this.totalHours; h++) {
      const line = gridLines.createDiv("fcp-grid-line");
      line.style.top = `${h * this.hourHeight}px`;
      line.style.height = `${this.slotHeight}px`;
      const halfLine = gridLines.createDiv("fcp-grid-line-half");
      halfLine.style.top = `${(h + 0.5) * this.hourHeight}px`;
      halfLine.style.height = `${this.slotHeight}px`;
    }
    weekDates.forEach((date, colIndex) => {
      const dateStr = this.formatDateIso(date);
      const colEl = columnsContainer.createDiv("fcp-day-column");
      colEl.dataset.date = dateStr;
      colEl.dataset.colIndex = colIndex.toString();
      colEl.addEventListener("click", async (e) => {
        if (e.target.closest(".fcp-entry-card"))
          return;
        const rect = colEl.getBoundingClientRect();
        const offsetY = e.clientY - rect.top;
        const slotIndex = Math.floor(offsetY / this.slotHeight);
        const maxSlots = this.totalHours * 2;
        const clampedSlot = Math.max(0, Math.min(slotIndex, maxSlots - 1));
        const startMinutes = this.startHour * 60 + clampedSlot * 30;
        const endMinutes = Math.min(startMinutes + 30, this.endHour * 60);
        const startTime = this.minutesToTimeStr(startMinutes);
        const endTime = this.minutesToTimeStr(endMinutes);
        const newEntry = await this.callbacks.onEntryCreate(dateStr, startTime, endTime);
        const newCard = this.renderEntryCard(colEl, newEntry);
        this.layoutDayColumn(dateStr);
        this.openEditModal(newEntry, newCard);
      });
      const dayEntries = this.entries.filter((e) => e.date === dateStr);
      dayEntries.forEach((entry) => {
        this.renderEntryCard(colEl, entry);
      });
      this.layoutDayColumn(dateStr);
    });
    setTimeout(() => {
      const scrollbarWidth = gridBody.offsetWidth - gridBody.clientWidth;
      if (scrollbarWidth > 0) {
        headerRow.style.paddingRight = `${scrollbarWidth}px`;
      } else {
        headerRow.style.paddingRight = "0px";
      }
    }, 0);
  }
  /**
   * Notion Calendar-style Overlap Clustering & Multi-Column Layout Algorithm
   */
  calculateDayOverlapLayout(entries) {
    const layoutMap = /* @__PURE__ */ new Map();
    if (entries.length === 0)
      return layoutMap;
    const intervals = entries.map((e) => {
      const startMins = this.snapTo30Min(this.timeStrToMinutes(e.startTime));
      let endMins = this.snapTo30Min(this.timeStrToMinutes(e.endTime));
      if (endMins <= startMins)
        endMins = startMins + 30;
      return { entry: e, startMins, endMins };
    });
    intervals.sort((a, b) => {
      if (a.startMins !== b.startMins)
        return a.startMins - b.startMins;
      return b.endMins - b.startMins - (a.endMins - a.startMins);
    });
    const clusters = [];
    let currentCluster = [];
    let clusterMaxEnd = -1;
    for (const item of intervals) {
      if (currentCluster.length === 0) {
        currentCluster.push(item);
        clusterMaxEnd = item.endMins;
      } else if (item.startMins < clusterMaxEnd) {
        currentCluster.push(item);
        clusterMaxEnd = Math.max(clusterMaxEnd, item.endMins);
      } else {
        clusters.push(currentCluster);
        currentCluster = [item];
        clusterMaxEnd = item.endMins;
      }
    }
    if (currentCluster.length > 0) {
      clusters.push(currentCluster);
    }
    for (const cluster of clusters) {
      const columnEndTimes = [];
      const itemCols = [];
      for (const item of cluster) {
        let placedCol = -1;
        for (let c = 0; c < columnEndTimes.length; c++) {
          if (columnEndTimes[c] <= item.startMins) {
            placedCol = c;
            columnEndTimes[c] = item.endMins;
            break;
          }
        }
        if (placedCol === -1) {
          placedCol = columnEndTimes.length;
          columnEndTimes.push(item.endMins);
        }
        itemCols.push({ entryId: item.entry.id, colIndex: placedCol });
      }
      const totalCols = Math.max(1, columnEndTimes.length);
      for (const ic of itemCols) {
        layoutMap.set(ic.entryId, { colIndex: ic.colIndex, totalCols });
      }
    }
    return layoutMap;
  }
  layoutDayColumn(dateStr) {
    const colEl = this.containerEl.querySelector(`.fcp-day-column[data-date="${dateStr}"]`);
    if (!colEl)
      return;
    const dayEntries = this.entries.filter((e) => e.date === dateStr);
    const layoutMap = this.calculateDayOverlapLayout(dayEntries);
    const cards = colEl.querySelectorAll(".fcp-entry-card");
    cards.forEach((card) => {
      const id = card.dataset.id;
      if (!id)
        return;
      const layout = layoutMap.get(id);
      if (layout) {
        const { colIndex, totalCols } = layout;
        if (totalCols <= 1) {
          card.style.left = "4px";
          card.style.width = "calc(100% - 8px)";
          card.style.right = "auto";
        } else {
          const widthPct = 100 / totalCols;
          const leftPct = colIndex * widthPct;
          card.style.left = `calc(${leftPct}% + 2px)`;
          card.style.width = `calc(${widthPct}% - 4px)`;
          card.style.right = "auto";
        }
      }
    });
  }
  renderCardContent(card, entry) {
    let content = card.querySelector(".fcp-entry-content");
    if (!content) {
      content = card.createDiv("fcp-entry-content");
    } else {
      content.empty();
    }
    const titleEl = content.createDiv("fcp-entry-title");
    titleEl.textContent = entry.title || "Untitled";
    if (entry.description && entry.description.trim()) {
      const descEl = content.createDiv("fcp-entry-desc");
      descEl.textContent = entry.description.trim();
      descEl.setAttribute("title", entry.description.trim());
    }
    const timeEl = content.createDiv("fcp-entry-time");
    timeEl.textContent = `${entry.startTime} - ${entry.endTime}`;
  }
  renderEntryCard(columnEl, entry) {
    const startMins = this.snapTo30Min(this.timeStrToMinutes(entry.startTime));
    let endMins = this.snapTo30Min(this.timeStrToMinutes(entry.endTime));
    if (endMins <= startMins) {
      endMins = startMins + 30;
    }
    entry.startTime = this.minutesToTimeStr(startMins);
    entry.endTime = this.minutesToTimeStr(endMins);
    const minStartScale = this.startHour * 60;
    const maxEndScale = this.endHour * 60;
    const clampedStart = Math.max(minStartScale, Math.min(startMins, maxEndScale));
    const clampedEnd = Math.max(clampedStart + 30, Math.min(endMins, maxEndScale));
    const topPx = Math.round((clampedStart - minStartScale) / 30) * this.slotHeight;
    const durationSlots = Math.max(1, Math.round((clampedEnd - clampedStart) / 30));
    const heightPx = durationSlots * this.slotHeight;
    const isFocused = this.callbacks.getFocusedTaskId() === entry.id;
    const isShort = durationSlots <= 1;
    const card = columnEl.createDiv(`fcp-entry-card type-${entry.type} ${isFocused ? "is-focused" : ""} ${isShort ? "is-short" : ""}`);
    card.style.top = `${topPx}px`;
    card.style.height = `${heightPx}px`;
    card.dataset.id = entry.id;
    card.createDiv("fcp-resize-handle top");
    card.createDiv("fcp-resize-handle bottom");
    this.renderCardContent(card, entry);
    card.addEventListener("click", (e) => {
      if (card.classList.contains("is-editing"))
        return;
      e.stopPropagation();
      this.callbacks.onTaskFocus(entry);
    });
    card.addEventListener("dblclick", (e) => {
      e.stopPropagation();
      this.openEditModal(entry, card);
    });
    card.addEventListener("contextmenu", (e) => {
      if (card.classList.contains("is-editing"))
        return;
      e.preventDefault();
      e.stopPropagation();
      const menu = new import_obsidian.Menu();
      menu.addItem((item) => {
        item.setTitle("Edit Details").setIcon("lucide-edit").onClick(() => {
          this.openEditModal(entry, card);
        });
      });
      menu.addItem((item) => {
        item.setTitle("Quick Rename").setIcon("lucide-edit-3").onClick(() => {
          this.enableCardInlineEdit(card, entry);
        });
      });
      menu.addItem((item) => {
        const nextType = entry.type === "task" ? "Event (Green)" : "Task (Pastel Blue)";
        item.setTitle(`Change to ${nextType}`).setIcon("lucide-refresh-cw").onClick(async () => {
          entry.type = entry.type === "task" ? "event" : "task";
          card.className = `fcp-entry-card type-${entry.type} ${this.callbacks.getFocusedTaskId() === entry.id ? "is-focused" : ""} ${parseFloat(card.style.height) <= this.slotHeight ? "is-short" : ""}`;
          await this.callbacks.onEntryUpdate(entry);
        });
      });
      menu.addItem((item) => {
        item.setTitle("Focus Pomodoro Timer").setIcon("lucide-timer").onClick(() => {
          this.callbacks.onTaskFocus(entry);
        });
      });
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle("Delete Entry").setIcon("lucide-trash-2").onClick(async () => {
          card.remove();
          await this.callbacks.onEntryDelete(entry);
          this.layoutDayColumn(entry.date);
        });
      });
      menu.showAtMouseEvent(e);
    });
    this.setupCardDrag(card, entry);
    return card;
  }
  openEditModal(entry, card) {
    new TaskEditModal(
      this.app,
      entry,
      async (updatedEntry) => {
        this.renderCardContent(card, updatedEntry);
        card.className = `fcp-entry-card type-${updatedEntry.type} ${this.callbacks.getFocusedTaskId() === updatedEntry.id ? "is-focused" : ""} ${parseFloat(card.style.height) <= this.slotHeight ? "is-short" : ""}`;
        const startMins = this.snapTo30Min(this.timeStrToMinutes(updatedEntry.startTime));
        let endMins = this.snapTo30Min(this.timeStrToMinutes(updatedEntry.endTime));
        if (endMins <= startMins)
          endMins = startMins + 30;
        const clampedStart = Math.max(this.startHour * 60, Math.min(startMins, this.endHour * 60));
        const clampedEnd = Math.max(clampedStart + 30, Math.min(endMins, this.endHour * 60));
        const topPx = Math.round((clampedStart - this.startHour * 60) / 30) * this.slotHeight;
        const heightPx = Math.max(1, Math.round((clampedEnd - clampedStart) / 30)) * this.slotHeight;
        card.style.top = `${topPx}px`;
        card.style.height = `${heightPx}px`;
        await this.callbacks.onEntryUpdate(updatedEntry);
        this.layoutDayColumn(updatedEntry.date);
      },
      async (deletedEntry) => {
        card.remove();
        await this.callbacks.onEntryDelete(deletedEntry);
        this.layoutDayColumn(deletedEntry.date);
      }
    ).open();
  }
  enableCardInlineEdit(card, entry) {
    const content = card.querySelector(".fcp-entry-content");
    if (!content || card.classList.contains("is-editing"))
      return;
    card.addClass("is-editing");
    content.innerHTML = "";
    const input = document.createElement("input");
    input.type = "text";
    input.className = "fcp-inline-input";
    input.value = entry.title || "";
    content.appendChild(input);
    let isReady = false;
    setTimeout(() => {
      isReady = true;
      input.focus();
      input.select();
    }, 100);
    let isFinished = false;
    const finishEdit = async (cancelled) => {
      if (isFinished)
        return;
      isFinished = true;
      card.removeClass("is-editing");
      if (!cancelled) {
        const newTitle = input.value.trim() || "New Task";
        entry.title = newTitle;
        await this.callbacks.onEntryUpdate(entry);
      }
      this.renderCardContent(card, entry);
    };
    input.addEventListener("blur", () => {
      if (!isReady)
        return;
      finishEdit(false);
    });
    input.addEventListener("keydown", (e) => {
      e.stopPropagation();
      if (e.key === "Enter") {
        e.preventDefault();
        finishEdit(false);
      } else if (e.key === "Escape") {
        e.preventDefault();
        finishEdit(true);
      }
    });
    input.addEventListener("keyup", (e) => e.stopPropagation());
    input.addEventListener("keypress", (e) => e.stopPropagation());
    input.addEventListener("mousedown", (e) => e.stopPropagation());
    input.addEventListener("mouseup", (e) => e.stopPropagation());
    input.addEventListener("click", (e) => e.stopPropagation());
    input.addEventListener("dblclick", (e) => e.stopPropagation());
  }
  setupCardDrag(card, entry) {
    let isDragging = false;
    let hasMoved = false;
    let dragMode = "move";
    let startY = 0;
    let startTop = 0;
    let startHeight = 0;
    const maxGridHeight = this.totalHours * this.hourHeight;
    const onMouseDown = (e) => {
      if (e.button !== 0 || card.classList.contains("is-editing"))
        return;
      const target = e.target;
      if (target.classList.contains("top")) {
        dragMode = "resize-top";
      } else if (target.classList.contains("bottom")) {
        dragMode = "resize-bottom";
      } else {
        dragMode = "move";
      }
      isDragging = true;
      hasMoved = false;
      startY = e.clientY;
      startTop = parseFloat(card.style.top) || 0;
      startHeight = parseFloat(card.style.height) || this.slotHeight;
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    };
    const onMouseMove = (e) => {
      if (!isDragging)
        return;
      const deltaY = e.clientY - startY;
      if (Math.abs(deltaY) > 3) {
        hasMoved = true;
        card.addClass("is-dragging");
      }
      const columnsContainer = this.containerEl.querySelector(".fcp-columns-container");
      if (dragMode === "move") {
        const rawTop = startTop + deltaY;
        const snappedTop = Math.max(0, Math.min(Math.round(rawTop / this.slotHeight) * this.slotHeight, maxGridHeight - startHeight));
        card.style.top = `${snappedTop}px`;
        if (columnsContainer) {
          const rect = columnsContainer.getBoundingClientRect();
          const colWidth = rect.width / 7;
          const relX = e.clientX - rect.left;
          const targetColIndex = Math.max(0, Math.min(6, Math.floor(relX / colWidth)));
          const targetColEl = columnsContainer.querySelector(`.fcp-day-column[data-col-index="${targetColIndex}"]`);
          if (targetColEl && card.parentElement !== targetColEl) {
            targetColEl.appendChild(card);
            hasMoved = true;
          }
        }
      } else if (dragMode === "resize-top") {
        const rawTop = startTop + deltaY;
        const snappedTop = Math.max(0, Math.min(Math.round(rawTop / this.slotHeight) * this.slotHeight, startTop + startHeight - this.slotHeight));
        const snappedHeight = startHeight + (startTop - snappedTop);
        card.style.top = `${snappedTop}px`;
        card.style.height = `${snappedHeight}px`;
      } else if (dragMode === "resize-bottom") {
        const rawHeight = startHeight + deltaY;
        const snappedHeight = Math.max(this.slotHeight, Math.min(Math.round(rawHeight / this.slotHeight) * this.slotHeight, maxGridHeight - startTop));
        card.style.height = `${snappedHeight}px`;
      }
      if (hasMoved) {
        const currentTop = parseFloat(card.style.top) || 0;
        const currentHeight = parseFloat(card.style.height) || this.slotHeight;
        if (currentHeight <= this.slotHeight) {
          card.addClass("is-short");
        } else {
          card.removeClass("is-short");
        }
        const startMins = this.startHour * 60 + Math.round(currentTop / this.slotHeight) * 30;
        const endMins = startMins + Math.round(currentHeight / this.slotHeight) * 30;
        const timeDiv = card.querySelector(".fcp-entry-time");
        if (timeDiv) {
          timeDiv.textContent = `${this.minutesToTimeStr(startMins)} - ${this.minutesToTimeStr(endMins)}`;
        }
      }
    };
    const onMouseUp = async (e) => {
      if (!isDragging)
        return;
      isDragging = false;
      card.removeClass("is-dragging");
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      if (!hasMoved)
        return;
      const oldDate = entry.date;
      const finalTop = parseFloat(card.style.top) || 0;
      const finalHeight = parseFloat(card.style.height) || this.slotHeight;
      const startSlot = Math.round(finalTop / this.slotHeight);
      const durationSlots = Math.max(1, Math.round(finalHeight / this.slotHeight));
      const startMins = this.startHour * 60 + startSlot * 30;
      const endMins = Math.min(this.endHour * 60, startMins + durationSlots * 30);
      const targetColEl = card.closest(".fcp-day-column");
      if (targetColEl && targetColEl.dataset.date) {
        entry.date = targetColEl.dataset.date;
      }
      entry.startTime = this.minutesToTimeStr(startMins);
      entry.endTime = this.minutesToTimeStr(endMins);
      await this.callbacks.onEntryUpdate(entry);
      this.layoutDayColumn(oldDate);
      if (entry.date !== oldDate) {
        this.layoutDayColumn(entry.date);
      }
    };
    card.addEventListener("mousedown", onMouseDown);
  }
  formatDateIso(d) {
    const y = d.getFullYear();
    const m = (d.getMonth() + 1).toString().padStart(2, "0");
    const day = d.getDate().toString().padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
  timeStrToMinutes(str) {
    if (!str)
      return 0;
    const parts = str.split(":").map(Number);
    return (parts[0] || 0) * 60 + (parts[1] || 0);
  }
  minutesToTimeStr(mins) {
    const h = Math.floor(mins / 60);
    const m = mins % 60;
    return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}`;
  }
  snapTo30Min(mins) {
    return Math.round(mins / 30) * 30;
  }
  updateFocusedTask(focusedTaskId) {
    if (!this.containerEl)
      return;
    const cards = this.containerEl.querySelectorAll(".fcp-entry-card");
    cards.forEach((cardEl) => {
      const htmlEl = cardEl;
      if (htmlEl.dataset.id === focusedTaskId) {
        htmlEl.addClass("is-focused");
      } else {
        htmlEl.removeClass("is-focused");
      }
    });
  }
  escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }
};

// src/views/MonthViewRender.ts
var MonthViewRenderComponent = class {
  constructor(containerEl, year, month, entries, pomoLogs, dailyHoursMap, callbacks) {
    this.containerEl = containerEl;
    this.currentYear = year;
    this.currentMonth = month;
    this.entries = entries;
    this.pomoLogs = pomoLogs;
    this.dailyHoursMap = dailyHoursMap;
    this.callbacks = callbacks;
    this.render();
  }
  update(year, month, entries, pomoLogs, dailyHoursMap) {
    this.currentYear = year;
    this.currentMonth = month;
    this.entries = entries;
    this.pomoLogs = pomoLogs;
    this.dailyHoursMap = dailyHoursMap;
    this.render();
  }
  getTaskColor(title) {
    const normalized = title.toLowerCase().trim();
    let hash = 0;
    for (let i = 0; i < normalized.length; i++) {
      hash = normalized.charCodeAt(i) + ((hash << 5) - hash);
    }
    const hue = Math.abs(hash) % 360;
    return `hsl(${hue}, 68%, 52%)`;
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("fcp-month-view-wrapper");
    const layoutContainer = this.containerEl.createDiv("fcp-month-layout-container");
    const gridPanel = layoutContainer.createDiv("fcp-month-grid-panel");
    const weekdaysHeader = gridPanel.createDiv("fcp-month-weekdays-header");
    const dayNames = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
    dayNames.forEach((d) => {
      const col = weekdaysHeader.createDiv("fcp-month-weekday-col");
      col.textContent = d;
    });
    const monthGrid = gridPanel.createDiv("fcp-month-grid");
    const firstDayDate = new Date(this.currentYear, this.currentMonth, 1);
    let startDayOfWeek = firstDayDate.getDay() - 1;
    if (startDayOfWeek === -1)
      startDayOfWeek = 6;
    const daysInMonth = new Date(this.currentYear, this.currentMonth + 1, 0).getDate();
    const daysInPrevMonth = new Date(this.currentYear, this.currentMonth, 0).getDate();
    const totalCells = Math.ceil((startDayOfWeek + daysInMonth) / 7) * 7;
    const todayIso = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    for (let i = 0; i < totalCells; i++) {
      let dayNumber;
      let monthOffset = 0;
      if (i < startDayOfWeek) {
        dayNumber = daysInPrevMonth - startDayOfWeek + i + 1;
        monthOffset = -1;
      } else if (i >= startDayOfWeek + daysInMonth) {
        dayNumber = i - (startDayOfWeek + daysInMonth) + 1;
        monthOffset = 1;
      } else {
        dayNumber = i - startDayOfWeek + 1;
        monthOffset = 0;
      }
      const cellYear = this.currentYear + (this.currentMonth + monthOffset < 0 ? -1 : this.currentMonth + monthOffset > 11 ? 1 : 0);
      const cellMonth = (this.currentMonth + monthOffset + 12) % 12;
      const cellIso = `${cellYear}-${(cellMonth + 1).toString().padStart(2, "0")}-${dayNumber.toString().padStart(2, "0")}`;
      const isToday = cellIso === todayIso;
      const isOtherMonth = monthOffset !== 0;
      const cellEl = monthGrid.createDiv(`fcp-month-cell ${isOtherMonth ? "other-month" : ""} ${isToday ? "is-today" : ""}`);
      const dailyHours = this.dailyHoursMap.get(cellIso) || 0;
      if (dailyHours > 0) {
        const intensity = Math.min(1, dailyHours / 8);
        const alpha = 0.12 + intensity * 0.58;
        cellEl.style.backgroundColor = `rgba(59, 130, 246, ${alpha.toFixed(2)})`;
        cellEl.style.borderColor = `rgba(59, 130, 246, ${(alpha + 0.2).toFixed(2)})`;
      }
      const cellHeader = cellEl.createDiv("fcp-month-cell-header");
      cellHeader.textContent = dayNumber.toString();
      cellEl.addEventListener("click", (e) => {
        if (e.target.closest(".fcp-month-event-item"))
          return;
        this.callbacks.onDayClick(cellIso);
      });
      const dayEvents = this.entries.filter((e) => e.date === cellIso && e.type === "event");
      if (dayEvents.length > 0) {
        const eventsContainer = cellEl.createDiv("fcp-month-events-container");
        dayEvents.forEach((evt) => {
          const evtEl = eventsContainer.createDiv("fcp-month-event-item");
          evtEl.innerHTML = `
            <span class="fcp-evt-dot"></span>
            <span class="fcp-evt-title">${this.escapeHtml(evt.title || "Event")}</span>
          `;
          evtEl.addEventListener("click", (e) => {
            e.stopPropagation();
            this.callbacks.onEventClick(evt);
          });
        });
      }
      if (dailyHours > 0) {
        const hoursTag = cellEl.createDiv("fcp-month-day-hours");
        const formattedHours = dailyHours % 1 === 0 ? `${dailyHours} Hrs` : `${dailyHours.toFixed(1)} Hrs`;
        hoursTag.textContent = formattedHours;
      }
    }
    this.renderBreakdownPanel(layoutContainer);
    setTimeout(() => {
      const scrollbarWidth = monthGrid.offsetWidth - monthGrid.clientWidth;
      if (scrollbarWidth > 0) {
        weekdaysHeader.style.paddingRight = `${scrollbarWidth}px`;
      } else {
        weekdaysHeader.style.paddingRight = "0px";
      }
    }, 0);
  }
  renderBreakdownPanel(parentEl) {
    const monthPrefix = `${this.currentYear}-${(this.currentMonth + 1).toString().padStart(2, "0")}`;
    const activityMap = /* @__PURE__ */ new Map();
    let grandTotalSeconds = 0;
    this.pomoLogs.forEach((log) => {
      if (log.type !== "work" || !log.date || !log.date.startsWith(monthPrefix))
        return;
      let rawTitle = (log.taskTitle || "").trim();
      if (!rawTitle || rawTitle.toLowerCase() === "general focus")
        return;
      const lower = rawTitle.toLowerCase();
      let displayTitle = rawTitle;
      let normKey = lower;
      if (log.taskId === "focus-drills" || lower === "drills" || lower.startsWith("[drill]") || lower.endsWith("drills") || lower.includes("drill:")) {
        displayTitle = "Drills";
        normKey = "drills";
      } else if (log.taskId === "focus-flashcards" || lower === "flashcards" || lower.startsWith("[flashcard]") || lower.includes("flashcard")) {
        displayTitle = "Flashcards";
        normKey = "flashcards";
      }
      const secs = log.durationSeconds || 0;
      if (secs <= 0)
        return;
      grandTotalSeconds += secs;
      if (activityMap.has(normKey)) {
        activityMap.get(normKey).totalSeconds += secs;
      } else {
        activityMap.set(normKey, {
          displayTitle,
          totalSeconds: secs,
          color: this.getTaskColor(displayTitle)
        });
      }
    });
    const grandTotalHours = grandTotalSeconds / 3600;
    const activities = Array.from(activityMap.values()).map((act) => ({
      displayTitle: act.displayTitle,
      totalHours: act.totalSeconds / 3600,
      color: act.color
    })).sort((a, b) => b.totalHours - a.totalHours);
    const breakdownPanel = parentEl.createDiv("fcp-month-breakdown-panel");
    const header = breakdownPanel.createDiv("fcp-breakdown-header");
    header.innerHTML = `
      <div class="fcp-breakdown-title">Statistics</div>
      <div class="fcp-breakdown-subtitle">${grandTotalHours.toFixed(1)} Focus Hrs</div>
    `;
    if (activities.length === 0 || grandTotalSeconds === 0) {
      const emptyMsg = breakdownPanel.createDiv("fcp-breakdown-empty");
      emptyMsg.textContent = "No focus time recorded this month.";
      return;
    }
    const barContainer = breakdownPanel.createDiv("fcp-stacked-bar");
    activities.forEach((act) => {
      const pct = act.totalHours / (grandTotalHours || 1) * 100;
      const segment = barContainer.createDiv("fcp-stacked-segment");
      segment.style.backgroundColor = act.color;
      segment.style.flex = `${pct}`;
      segment.title = `${act.displayTitle}: ${act.totalHours.toFixed(1)}h (${pct.toFixed(0)}%)`;
    });
    const legend = breakdownPanel.createDiv("fcp-breakdown-legend");
    activities.forEach((act) => {
      const pct = act.totalHours / (grandTotalHours || 1) * 100;
      const item = legend.createDiv("fcp-legend-item");
      item.innerHTML = `
        <div class="fcp-legend-left">
          <span class="fcp-legend-dot" style="background-color: ${act.color};"></span>
          <span class="fcp-legend-name" title="${this.escapeHtml(act.displayTitle)}">${this.escapeHtml(act.displayTitle)}</span>
        </div>
        <div class="fcp-legend-right">
          <span class="fcp-legend-hours">${act.totalHours.toFixed(1)}h</span>
          <span class="fcp-legend-pct">${pct.toFixed(0)}%</span>
        </div>
      `;
    });
  }
  escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }
};

// src/views/CalendarView.ts
var VIEW_TYPE_FOCUS_CALENDAR = "focus-calendar-pomodoro-view";
var FocusCalendarView = class extends import_obsidian2.ItemView {
  constructor(leaf, storage, pomodoro) {
    super(leaf);
    this.viewMode = "week";
    this.currentDate = /* @__PURE__ */ new Date();
    this.headerComponent = null;
    this.weekComponent = null;
    this.monthComponent = null;
    this.entries = [];
    this.pomoLogs = [];
    this.storage = storage;
    this.pomodoro = pomodoro;
  }
  getViewType() {
    return VIEW_TYPE_FOCUS_CALENDAR;
  }
  getDisplayText() {
    return "Calendar & Focus";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    await this.refreshData();
    this.renderView();
  }
  async refreshData() {
    const yearMonth = this.getYearMonthString(this.currentDate);
    this.entries = await this.storage.loadEntriesForMonth(yearMonth);
    this.pomoLogs = await this.storage.loadPomodoroLogsForMonth(yearMonth);
  }
  renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("fcp-main-container");
    const navBar = container.createDiv("fcp-nav-bar");
    const leftNav = navBar.createDiv("fcp-nav-left");
    const todayBtn = leftNav.createEl("button", { cls: "fcp-btn", text: "Today" });
    todayBtn.onclick = async () => {
      this.currentDate = /* @__PURE__ */ new Date();
      await this.refreshData();
      this.renderView();
    };
    const prevBtn = leftNav.createEl("button", { cls: "fcp-icon-btn", ariaLabel: "Previous" });
    prevBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>`;
    prevBtn.onclick = async () => {
      if (this.viewMode === "week") {
        this.currentDate.setDate(this.currentDate.getDate() - 7);
      } else {
        this.currentDate.setMonth(this.currentDate.getMonth() - 1);
      }
      await this.refreshData();
      this.renderView();
    };
    const nextBtn = leftNav.createEl("button", { cls: "fcp-icon-btn", ariaLabel: "Next" });
    nextBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>`;
    nextBtn.onclick = async () => {
      if (this.viewMode === "week") {
        this.currentDate.setDate(this.currentDate.getDate() + 7);
      } else {
        this.currentDate.setMonth(this.currentDate.getMonth() + 1);
      }
      await this.refreshData();
      this.renderView();
    };
    const dateTitle = leftNav.createDiv("fcp-nav-date-title");
    dateTitle.textContent = this.currentDate.toLocaleDateString("en-US", { month: "long", year: "numeric" });
    const modeSwitch = navBar.createDiv("fcp-mode-switch");
    const weekBtn = modeSwitch.createEl("button", {
      cls: `fcp-switch-btn ${this.viewMode === "week" ? "active" : ""}`,
      text: "Week"
    });
    weekBtn.onclick = () => {
      if (this.viewMode !== "week") {
        this.viewMode = "week";
        this.renderView();
      }
    };
    const monthBtn = modeSwitch.createEl("button", {
      cls: `fcp-switch-btn ${this.viewMode === "month" ? "active" : ""}`,
      text: "Month"
    });
    monthBtn.onclick = () => {
      if (this.viewMode !== "month") {
        this.viewMode = "month";
        this.renderView();
      }
    };
    const pomoHeaderContainer = container.createDiv("fcp-header-slot");
    const totalHours = this.calculateTotalHours();
    const imminentEvent = this.getImminentEvent();
    this.headerComponent = new PomodoroHeaderComponent(
      pomoHeaderContainer,
      this.pomodoro,
      this.viewMode,
      totalHours,
      imminentEvent
    );
    const viewAreaContainer = container.createDiv("fcp-view-area");
    if (this.viewMode === "week") {
      const weekStart = this.getMondayOfWeek(this.currentDate);
      this.weekComponent = new WeekViewRenderComponent(
        this.app,
        viewAreaContainer,
        weekStart,
        this.entries,
        {
          onEntryCreate: async (date, startTime, endTime) => {
            const newEntry = {
              id: "entry-" + Date.now(),
              title: "",
              date,
              startTime,
              endTime,
              type: "task",
              createdAt: Date.now(),
              updatedAt: Date.now()
            };
            this.entries.push(newEntry);
            await this.storage.saveEntry(newEntry);
            return newEntry;
          },
          onEntryUpdate: async (entry) => {
            entry.updatedAt = Date.now();
            await this.storage.saveEntry(entry);
            this.updateHeaderStats();
          },
          onEntryDelete: async (entry) => {
            var _a;
            await this.storage.deleteEntry(entry.id, entry.date);
            this.entries = this.entries.filter((e) => e.id !== entry.id);
            if (((_a = this.pomodoro.getFocusedTask()) == null ? void 0 : _a.id) === entry.id) {
              this.pomodoro.setFocusedTask(null);
            }
            this.updateHeaderStats();
          },
          onTaskFocus: (entry) => {
            var _a, _b;
            const currentFocused = this.pomodoro.getFocusedTask();
            if ((currentFocused == null ? void 0 : currentFocused.id) === entry.id) {
              this.pomodoro.setFocusedTask(null);
              (_a = this.weekComponent) == null ? void 0 : _a.updateFocusedTask(null);
            } else {
              this.pomodoro.setFocusedTask(entry);
              (_b = this.weekComponent) == null ? void 0 : _b.updateFocusedTask(entry.id);
            }
          },
          getFocusedTaskId: () => {
            var _a;
            return (_a = this.pomodoro.getFocusedTask()) == null ? void 0 : _a.id;
          }
        }
      );
    } else {
      this.monthComponent = new MonthViewRenderComponent(
        viewAreaContainer,
        this.currentDate.getFullYear(),
        this.currentDate.getMonth(),
        this.entries,
        this.pomoLogs,
        this.buildDailyHoursMap(),
        {
          onDayClick: async (dateIso) => {
            this.currentDate = /* @__PURE__ */ new Date(dateIso + "T12:00:00");
            this.viewMode = "week";
            await this.refreshData();
            this.renderView();
          },
          onEventClick: (entry) => {
          }
        }
      );
    }
  }
  updateHeaderStats() {
    if (this.headerComponent) {
      this.headerComponent.update(this.viewMode, this.calculateTotalHours(), this.getImminentEvent());
    }
  }
  getImminentEvent() {
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    const todayTime = (/* @__PURE__ */ new Date(todayStr + "T00:00:00")).getTime();
    const futureEvents = this.entries.filter((e) => e.type === "event" && e.date >= todayStr);
    if (futureEvents.length === 0)
      return null;
    futureEvents.sort((a, b) => a.date.localeCompare(b.date));
    const closest = futureEvents[0];
    const eventTime = (/* @__PURE__ */ new Date(closest.date + "T00:00:00")).getTime();
    const diffDays = Math.round((eventTime - todayTime) / (1e3 * 60 * 60 * 24));
    return {
      title: closest.title || "Untitled Event",
      daysAway: Math.max(0, diffDays)
    };
  }
  buildDailyHoursMap() {
    const map = /* @__PURE__ */ new Map();
    this.pomoLogs.forEach((log) => {
      if (log.type === "work" && log.date) {
        const current = map.get(log.date) || 0;
        map.set(log.date, current + log.durationSeconds / 3600);
      }
    });
    return map;
  }
  calculateTotalHours() {
    let totalSeconds = 0;
    if (this.viewMode === "week") {
      const weekStart = this.getMondayOfWeek(this.currentDate);
      const weekEnd = new Date(weekStart);
      weekEnd.setDate(weekEnd.getDate() + 7);
      const weekStartIso = weekStart.toISOString().substring(0, 10);
      const weekEndIso = weekEnd.toISOString().substring(0, 10);
      this.pomoLogs.forEach((log) => {
        if (log.type === "work" && log.date >= weekStartIso && log.date < weekEndIso) {
          totalSeconds += log.durationSeconds;
        }
      });
    } else {
      this.pomoLogs.forEach((log) => {
        if (log.type === "work") {
          totalSeconds += log.durationSeconds;
        }
      });
    }
    return totalSeconds / 3600;
  }
  getMondayOfWeek(d) {
    const date = new Date(d);
    const day = date.getDay();
    const diff = date.getDate() - day + (day === 0 ? -6 : 1);
    return new Date(date.setDate(diff));
  }
  getYearMonthString(d) {
    const y = d.getFullYear();
    const m = (d.getMonth() + 1).toString().padStart(2, "0");
    return `${y}-${m}`;
  }
};

// src/storage.ts
var import_obsidian3 = require("obsidian");
var StorageManager = class {
  constructor(app, settingsGetter) {
    this.isLocalSaving = false;
    this.app = app;
    this.settingsGetter = settingsGetter;
  }
  get dataFolder() {
    return (0, import_obsidian3.normalizePath)(this.settingsGetter().dataDirectory || "calendar-data");
  }
  async ensureDataFolderExists() {
    const folderPath = this.dataFolder;
    const exists = await this.app.vault.adapter.exists(folderPath);
    if (!exists) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  getMonthFilePath(yearMonth) {
    return (0, import_obsidian3.normalizePath)(`${this.dataFolder}/entries-${yearMonth}.json`);
  }
  getPomodoroLogFilePath(yearMonth) {
    return (0, import_obsidian3.normalizePath)(`${this.dataFolder}/focus-logs-${yearMonth}.json`);
  }
  async loadEntriesForMonth(yearMonth) {
    await this.ensureDataFolderExists();
    const path = this.getMonthFilePath(yearMonth);
    try {
      const exists = await this.app.vault.adapter.exists(path);
      if (!exists) {
        return [];
      }
      const content = await this.app.vault.adapter.read(path);
      return JSON.parse(content);
    } catch (e) {
      console.error(`Failed to read calendar entries for ${yearMonth}:`, e);
      return [];
    }
  }
  async saveEntriesForMonth(yearMonth, entries) {
    await this.ensureDataFolderExists();
    const path = this.getMonthFilePath(yearMonth);
    const data = JSON.stringify(entries, null, 2);
    this.isLocalSaving = true;
    await this.app.vault.adapter.write(path, data);
    setTimeout(() => {
      this.isLocalSaving = false;
    }, 500);
  }
  async saveEntry(entry) {
    const yearMonth = entry.date.substring(0, 7);
    const currentEntries = await this.loadEntriesForMonth(yearMonth);
    const existingIdx = currentEntries.findIndex((e) => e.id === entry.id);
    if (existingIdx >= 0) {
      currentEntries[existingIdx] = entry;
    } else {
      currentEntries.push(entry);
    }
    await this.saveEntriesForMonth(yearMonth, currentEntries);
  }
  async deleteEntry(entryId, date) {
    const yearMonth = date.substring(0, 7);
    const currentEntries = await this.loadEntriesForMonth(yearMonth);
    const filtered = currentEntries.filter((e) => e.id !== entryId);
    await this.saveEntriesForMonth(yearMonth, filtered);
  }
  async logPomodoroSession(session) {
    await this.ensureDataFolderExists();
    const yearMonth = session.date.substring(0, 7);
    const path = this.getPomodoroLogFilePath(yearMonth);
    let logs = [];
    try {
      if (await this.app.vault.adapter.exists(path)) {
        const content = await this.app.vault.adapter.read(path);
        logs = JSON.parse(content);
      }
    } catch (e) {
      logs = [];
    }
    const rawTitle = (session.taskTitle || "").trim();
    if (!rawTitle)
      return;
    const titleKey = rawTitle.toLowerCase();
    const existingIdx = logs.findIndex(
      (l) => l.date === session.date && l.type === session.type && (l.taskTitle || "").trim().toLowerCase() === titleKey
    );
    if (existingIdx >= 0) {
      logs[existingIdx].durationSeconds += session.durationSeconds;
      logs[existingIdx].completedAt = session.completedAt;
      if (session.taskId)
        logs[existingIdx].taskId = session.taskId;
    } else {
      const cleanId = `${session.date}:${titleKey}`;
      logs.push({
        id: cleanId,
        taskId: session.taskId,
        taskTitle: rawTitle,
        type: session.type,
        durationSeconds: session.durationSeconds,
        completedAt: session.completedAt,
        date: session.date
      });
    }
    this.isLocalSaving = true;
    await this.app.vault.adapter.write(path, JSON.stringify(logs, null, 2));
    setTimeout(() => {
      this.isLocalSaving = false;
    }, 500);
  }
  async loadPomodoroLogsForMonth(yearMonth) {
    await this.ensureDataFolderExists();
    const path = this.getPomodoroLogFilePath(yearMonth);
    try {
      if (!await this.app.vault.adapter.exists(path))
        return [];
      const content = await this.app.vault.adapter.read(path);
      return JSON.parse(content);
    } catch (e) {
      return [];
    }
  }
};

// src/pomodoro.ts
var import_obsidian4 = require("obsidian");
var PomodoroManager = class {
  constructor(settingsGetter, onStateChange, onSessionComplete, playAudioCallback, onBreakStartCallback) {
    this.mode = "work";
    this.isRunning = false;
    this.timeLeftSeconds = 40 * 60;
    this.totalDurationSeconds = 40 * 60;
    this.timerId = null;
    this.focusedTask = null;
    this.activeWorkSecondsAccumulated = 0;
    this.settingsGetter = settingsGetter;
    this.onStateChange = onStateChange;
    this.onSessionComplete = onSessionComplete;
    this.playAudioCallback = playAudioCallback;
    this.onBreakStartCallback = onBreakStartCallback;
    this.resetTimer();
  }
  getSettings() {
    return this.settingsGetter();
  }
  getIsRunning() {
    return this.isRunning;
  }
  getState() {
    return {
      mode: this.mode,
      isRunning: this.isRunning,
      timeLeftSeconds: this.timeLeftSeconds,
      totalDurationSeconds: this.totalDurationSeconds,
      focusedTask: this.focusedTask
    };
  }
  setFocusedTask(task) {
    var _a;
    if (((_a = this.focusedTask) == null ? void 0 : _a.id) === (task == null ? void 0 : task.id))
      return;
    if (this.isRunning && this.mode === "work") {
      this.flushWorkLog();
    }
    this.focusedTask = task;
    if (!task && this.mode === "work" && this.isRunning) {
      this.pause();
      new import_obsidian4.Notice("\u23F8\uFE0F Pomodoro timer paused: Task focus cleared.", 3e3);
    }
    this.notifyState();
  }
  getFocusedTask() {
    return this.focusedTask;
  }
  start() {
    if (this.isRunning)
      return true;
    if (this.mode === "work" && !this.focusedTask) {
      new import_obsidian4.Notice("\u26A0\uFE0F Select a task from the calendar before starting the Pomodoro timer!", 4e3);
      return false;
    }
    this.isRunning = true;
    this.timerId = window.setInterval(() => this.tick(), 1e3);
    this.notifyState();
    return true;
  }
  pause() {
    if (!this.isRunning)
      return;
    this.isRunning = false;
    if (this.timerId !== null) {
      clearInterval(this.timerId);
      this.timerId = null;
    }
    this.flushWorkLog();
    this.notifyState();
  }
  togglePlayPause() {
    if (this.isRunning) {
      this.pause();
    } else {
      this.start();
    }
  }
  resetTimer() {
    this.pause();
    this.flushWorkLog();
    const settings = this.settingsGetter();
    if (this.mode === "work") {
      this.totalDurationSeconds = (settings.workDurationMinutes || 40) * 60;
    } else {
      this.totalDurationSeconds = (settings.breakDurationMinutes || 10) * 60;
    }
    this.timeLeftSeconds = this.totalDurationSeconds;
    this.notifyState();
  }
  switchMode(newMode) {
    this.pause();
    this.flushWorkLog();
    this.mode = newMode || (this.mode === "work" ? "break" : "work");
    if (this.mode === "break" && this.onBreakStartCallback) {
      this.onBreakStartCallback();
    }
    this.resetTimer();
  }
  tick() {
    if (this.mode === "work") {
      this.activeWorkSecondsAccumulated++;
    }
    if (this.timeLeftSeconds > 0) {
      this.timeLeftSeconds--;
      this.notifyState();
    } else {
      this.onCompleted();
    }
  }
  flushWorkLog() {
    if (this.mode === "work" && this.activeWorkSecondsAccumulated > 0) {
      if (!this.focusedTask || !this.focusedTask.title) {
        this.activeWorkSecondsAccumulated = 0;
        return;
      }
      const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
      const session = {
        id: "session-" + Date.now(),
        taskId: this.focusedTask.id,
        taskTitle: this.focusedTask.title,
        type: "work",
        durationSeconds: this.activeWorkSecondsAccumulated,
        completedAt: Date.now(),
        date: today
      };
      this.activeWorkSecondsAccumulated = 0;
      this.onSessionComplete(session);
    }
  }
  onCompleted() {
    this.pause();
    this.flushWorkLog();
    const settings = this.settingsGetter();
    const completedMode = this.mode;
    if (completedMode === "work") {
      const soundPath = (settings.focusEndSoundPath || "").trim();
      if (soundPath !== "" && this.playAudioCallback) {
        this.playAudioCallback(soundPath);
      }
    } else {
      const soundPath = (settings.breakEndSoundPath || "").trim();
      if (soundPath !== "" && this.playAudioCallback) {
        this.playAudioCallback(soundPath);
      }
    }
    this.mode = this.mode === "work" ? "break" : "work";
    if (this.mode === "break" && this.onBreakStartCallback) {
      this.onBreakStartCallback();
    }
    this.resetTimer();
    if (settings.autoStartBreak && this.mode === "break") {
      this.start();
    }
  }
  notifySettingsUpdated() {
    if (!this.isRunning) {
      this.resetTimer();
    }
  }
  notifyState() {
    this.onStateChange(this.getState());
  }
};

// src/settings.ts
var import_obsidian5 = require("obsidian");
var FocusCalendarSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Calendar & Focus Settings" });
    containerEl.createEl("h3", { text: "Pomodoro Timer" });
    new import_obsidian5.Setting(containerEl).setName("Work Duration (minutes)").setDesc("Length of work pomodoro sessions in minutes.").addText((text) => text.setPlaceholder("40").setValue(this.plugin.settings.workDurationMinutes.toString()).onChange(async (value) => {
      const val = parseInt(value, 10);
      if (!isNaN(val) && val > 0) {
        this.plugin.settings.workDurationMinutes = val;
        await this.plugin.saveSettings();
        this.plugin.pomodoro.notifySettingsUpdated();
      }
    }));
    new import_obsidian5.Setting(containerEl).setName("Break Duration (minutes)").setDesc("Length of break pomodoro sessions in minutes.").addText((text) => text.setPlaceholder("10").setValue(this.plugin.settings.breakDurationMinutes.toString()).onChange(async (value) => {
      const val = parseInt(value, 10);
      if (!isNaN(val) && val > 0) {
        this.plugin.settings.breakDurationMinutes = val;
        await this.plugin.saveSettings();
        this.plugin.pomodoro.notifySettingsUpdated();
      }
    }));
    new import_obsidian5.Setting(containerEl).setName("Auto-Start Break").setDesc("Automatically start break timer when a work pomodoro session completes.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoStartBreak).onChange(async (value) => {
      this.plugin.settings.autoStartBreak = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Audio Notifications" });
    const focusSoundSetting = new import_obsidian5.Setting(containerEl).setName("Focus Completed Sound (Vault MP3 Path)").setDesc("Audio file in your vault played when focus/work time ends and break starts (e.g. Sounds/bell.mp3). Leave blank for no sound.").addText((text) => text.setPlaceholder("Sounds/bell.mp3").setValue(this.plugin.settings.focusEndSoundPath || "").onChange(async (value) => {
      this.plugin.settings.focusEndSoundPath = value.trim();
      await this.plugin.saveSettings();
    })).addButton((button) => button.setButtonText("\u{1F50A} Test").setTooltip("Play preview of the Focus completion sound").onClick(async () => {
      const path = (this.plugin.settings.focusEndSoundPath || "").trim();
      if (!path) {
        new import_obsidian5.Notice("\u26A0\uFE0F No sound file path specified.");
        return;
      }
      const ok = await this.plugin.playVaultAudio(path, true);
      if (ok) {
        new import_obsidian5.Notice(`\u25B6\uFE0F Playing: ${path}`);
      }
    }));
    const breakSoundSetting = new import_obsidian5.Setting(containerEl).setName("Break Completed Sound (Vault MP3 Path)").setDesc("Audio file in your vault played when break time ends and focus starts (e.g. Sounds/chime.mp3). Leave blank for no sound.").addText((text) => text.setPlaceholder("Sounds/chime.mp3").setValue(this.plugin.settings.breakEndSoundPath || "").onChange(async (value) => {
      this.plugin.settings.breakEndSoundPath = value.trim();
      await this.plugin.saveSettings();
    })).addButton((button) => button.setButtonText("\u{1F50A} Test").setTooltip("Play preview of the Break completion sound").onClick(async () => {
      const path = (this.plugin.settings.breakEndSoundPath || "").trim();
      if (!path) {
        new import_obsidian5.Notice("\u26A0\uFE0F No sound file path specified.");
        return;
      }
      const ok = await this.plugin.playVaultAudio(path, true);
      if (ok) {
        new import_obsidian5.Notice(`\u25B6\uFE0F Playing: ${path}`);
      }
    }));
    containerEl.createEl("h3", { text: "Storage" });
    new import_obsidian5.Setting(containerEl).setName("Data Storage Directory").setDesc("Folder path in your vault where calendar JSON data files are saved.").addText((text) => text.setPlaceholder("calendar-data").setValue(this.plugin.settings.dataDirectory).onChange(async (value) => {
      this.plugin.settings.dataDirectory = value.trim() || "calendar-data";
      await this.plugin.saveSettings();
    }));
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  workDurationMinutes: 40,
  breakDurationMinutes: 10,
  dataDirectory: "calendar-data",
  autoStartBreak: true,
  focusEndSoundPath: "",
  breakEndSoundPath: ""
};
var FocusCalendarPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.statusBarItem = null;
    this.isAutoStarted = false;
  }
  async onload() {
    await this.loadSettings();
    this.storage = new StorageManager(this.app, () => this.settings);
    this.statusBarItem = this.addStatusBarItem();
    this.pomodoro = new PomodoroManager(
      () => this.settings,
      (state) => {
        this.updateStatusBar(state);
        this.app.workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR).forEach((leaf) => {
          if (leaf.view instanceof FocusCalendarView) {
            leaf.view.updateHeaderStats();
          }
        });
      },
      async (session) => {
        await this.storage.logPomodoroSession(session);
        this.app.workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR).forEach((leaf) => {
          if (leaf.view instanceof FocusCalendarView) {
            leaf.view.refreshData().then(() => leaf.view.renderView());
          }
        });
      },
      (filePath) => this.playVaultAudio(filePath),
      () => this.app.workspace.trigger("focus-calendar:break-start")
    );
    this.updateStatusBar(this.pomodoro.getState());
    this.registerView(
      VIEW_TYPE_FOCUS_CALENDAR,
      (leaf) => new FocusCalendarView(leaf, this.storage, this.pomodoro)
    );
    this.addRibbonIcon("calendar-clock", "Calendar & Focus", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-focus-calendar-view",
      name: "Open Calendar & Focus View",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new FocusCalendarSettingTab(this.app, this));
    const handleDrillComplete = async (data) => {
      if (this.isAutoStarted) {
        this.endAutoStudySession();
        return;
      }
      const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
      await this.storage.logPomodoroSession({
        id: "drill-" + Date.now(),
        taskId: "focus-drills",
        taskTitle: "Drills",
        type: "work",
        durationSeconds: data.timeSec || 0,
        completedAt: Date.now(),
        date: today
      });
    };
    const handleReviewComplete = async (data) => {
      if (this.isAutoStarted) {
        this.endAutoStudySession();
        return;
      }
      const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
      await this.storage.logPomodoroSession({
        id: "review-" + Date.now(),
        taskId: "focus-flashcards",
        taskTitle: "Flashcards",
        type: "work",
        durationSeconds: data.timeSec || 0,
        completedAt: Date.now(),
        date: today
      });
    };
    this.registerEvent(this.app.workspace.on("spaced-repetition:drill-complete", handleDrillComplete));
    this.registerEvent(this.app.workspace.on("spaced-repetition:review-complete", handleReviewComplete));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.storage && this.storage.isLocalSaving)
          return;
        if (file.path.startsWith(this.settings.dataDirectory) && file.path.endsWith(".json")) {
          this.app.workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR).forEach((leaf) => {
            if (leaf.view instanceof FocusCalendarView) {
              leaf.view.refreshData().then(() => leaf.view.renderView());
            }
          });
        }
      })
    );
  }
  updateStatusBar(state) {
    if (!this.statusBarItem)
      return;
    const mins = Math.floor(state.timeLeftSeconds / 60);
    const secs = state.timeLeftSeconds % 60;
    const timeFormatted = `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
    const taskTitle = state.focusedTask ? state.focusedTask.title : state.mode === "work" ? "WORK" : "BREAK";
    const statusIcon = state.isRunning ? "\u23F1\uFE0F" : "\u23F8\uFE0F";
    this.statusBarItem.setText(`${statusIcon} ${timeFormatted} [${taskTitle}]`);
  }
  startAutoFlashcardSession() {
    const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    this.pomodoro.setFocusedTask({
      id: "focus-flashcards",
      title: "Flashcards",
      startTime: "00:00",
      endTime: "00:00",
      date: today,
      type: "task",
      createdAt: Date.now(),
      updatedAt: Date.now()
    });
    this.isAutoStarted = true;
    if (!this.pomodoro.getIsRunning()) {
      this.pomodoro.start();
    }
    return true;
  }
  startAutoDrillSession() {
    const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    if (!this.pomodoro.getFocusedTask()) {
      this.pomodoro.setFocusedTask({
        id: "focus-drills",
        title: "Drills",
        startTime: "00:00",
        endTime: "00:00",
        date: today,
        type: "task",
        createdAt: Date.now(),
        updatedAt: Date.now()
      });
    }
    this.isAutoStarted = true;
    if (!this.pomodoro.getIsRunning()) {
      this.pomodoro.start();
    }
    return true;
  }
  startAutoStudySession(title) {
    const lower = (title || "").toLowerCase();
    if (lower.includes("flashcard")) {
      return this.startAutoFlashcardSession();
    }
    if (lower.includes("drill")) {
      return this.startAutoDrillSession();
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
    this.pomodoro.setFocusedTask({
      id: "auto-" + Date.now(),
      title,
      startTime: "00:00",
      endTime: "00:00",
      date: today,
      type: "task",
      createdAt: Date.now(),
      updatedAt: Date.now()
    });
    this.isAutoStarted = true;
    if (!this.pomodoro.getIsRunning()) {
      this.pomodoro.start();
    }
    return true;
  }
  endAutoStudySession() {
    if (this.isAutoStarted) {
      this.pomodoro.pause();
      this.isAutoStarted = false;
    }
  }
  async playVaultAudio(filePath, showNoticeOnFail = false) {
    try {
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian6.TFile) {
        const resourcePath = this.app.vault.getResourcePath(file);
        const audio = new Audio(resourcePath);
        audio.volume = 0.5;
        await audio.play();
        return true;
      } else {
        const msg = `Focus Calendar: Sound file not found at path: "${filePath}"`;
        console.warn(msg);
        if (showNoticeOnFail) {
          new import_obsidian6.Notice(`\u26A0\uFE0F ${msg}`, 4e3);
        }
        return false;
      }
    } catch (err) {
      console.error("Focus Calendar: Failed to play audio file from vault", err);
      if (showNoticeOnFail) {
        new import_obsidian6.Notice(`\u274C Failed to play audio file: ${filePath}`, 4e3);
      }
      return false;
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_FOCUS_CALENDAR);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_FOCUS_CALENDAR,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  onunload() {
    this.pomodoro.pause();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
